### ISSUE TITLE
OSX: Attempt to index a nil value (global 'cfg')

### ISSUE THREAD

**Issue by redorav** [premake/premake-core#1013]
I have the following code that works on Windows:

```lua
workspace("Project")
	configurations { "Debug", "Release" }
	location ("Build/".._ACTION)
	architecture("x64")
	
	configuration "Debug"
		defines { "DEBUG", "_DEBUG" }
		symbols "on"

	configuration "Release"
		defines { "NDEBUG" }
		optimize "on"
	
project ("Project")
	kind("StaticLib")
	language("C++")
	
	files { "Source/lib/**.cpp", "Source/lib/**.hpp", "Source/lib/**.h" }
	includedirs { "Source/lib/include" }
	
	filter{"configurations:"} -- Removing this on Mac causes it to fail but works in Windows
	
	postbuildcommands 
	{
		"{copy} %{cfg.buildcfg.abspath} ../../Binaries/".."Project"..".".._ACTION..".%{cfg.buildcfg:lower()}".."%{cfg.buildtarget.extension}*"
	}
```

Somehow on the Mac cfg becomes nil if I don't do an explicit filter("configurations:") with basically no filter applied to it. On Windows it works, but on Mac it fails.

**Comment by samsinsane** [comment]
What action were you using on macOS? `xcode4`?

**Comment by redorav** [comment]
Yes, xcode4. Should I be using something else?

**Comment by samsinsane** [comment]
No no, just wanted to verify that it was indeed `xcode4` and not `gmake` or `codelite`, or even the `vs*` actions.

**Comment by samsinsane** [comment]
[This](https://github.com/premake/premake-core/blob/0eda22c602567e8b2efb9f1ba104fa766d5adbd4/modules/xcode/xcode_common.lua#L758-L793) will be the issue, it specifically handles the project level configurations, whereas VS [doesn't](https://github.com/premake/premake-core/blob/0eda22c602567e8b2efb9f1ba104fa766d5adbd4/modules/vstudio/vs2010_vcxproj.lua#L303-L307). I guess the fix would be to drop the optimization for project level items. @starkos thoughts?

**Comment by starkos** [comment]
It seems like the Xcode exporter is trying to do the right thing here. I'm not clear on why `cfg` is becoming nil.

**Comment by samsinsane** [comment]
I looked into this more and tested it out, `tr.project[which]` triggers `detoken.expand` which won't have a `cfg` because it's a project not a configuration (like `cfg[which]`). `tr.project[which]` is done in two places, one in `xcode.PBXShellScriptBuildPhase` as linked above and another in `xcode_PBXAggregateOrNativeTarget` [here](https://github.com/premake/premake-core/blob/5913b0ebaa3880572b8a140a408d03b2f1c6cbf7/modules/xcode/xcode_common.lua#L756-L767). Removing both calls resolves the error, and generates the output as expected.

@starkos does removing the optimizations make sense to you too? I don't really see how the Xcode exporter was trying to do the right thing, but you have a much better idea of how the exporter works, as well as the configset and detoken systems.

**Comment by starkos** [comment]
Digging into this some more. Yes, the code [here](https://github.com/premake/premake-core/blob/1692363/modules/xcode/xcode_common.lua#L752-L754) and [here](https://github.com/premake/premake-core/blob/1692363/modules/xcode/xcode_common.lua#L937) should be removed. We should only try to pull commands from configs, not projects.

I should be back home next week, and am planning to spend some time working Premake5 issues on my next cycle. I can tackle this one then.
