### ISSUE TITLE
When will the next release come?

### ISSUE THREAD

**Issue by mercury233** [premake/premake-core#1026]
Waiting for a stable version to update one project from premake4 to premake5.
Is there any plan for the next release?

**Comment by starkos** [comment]
Sorry for the delay on this—everyone's swamped.

I will start an issue for the 5.0 release and list the things I know need to be done. It won't help with a release date, but should give some sense on how much work remains (hint: a lot).

I will follow up this ticket when done.

**Comment by TurkeyMan** [comment]
@starkos Do you have any updated thoughts on this? I'd love to see that release schedule maintained somewhere so we can gauge where we're at.

**Comment by samsinsane** [comment]
Maybe we can look into automating our alpha releases for the time being? [AppVeyor](https://www.appveyor.com/docs/deployment/github/) and [Travis CI](https://docs.travis-ci.com/user/deployment/releases/) both have documentation on doing this, but I'm not overly sure what's involved in the release process for Premake? Would be nice to have "monthly" releases, the last alpha was just over 11 months ago.

Personally, I don't really have the time to update our version of Premake to non-releases, so having a more consistent release cycle would make it easier for me to contribute work changes back. I've been pushing for time to do Premake work so that I can start pushing all the random hacks and patches back to master for the next release.

> As things stand, I can only work on things that at least have the potential to provide short-term revenue.

The developer of ImGui setup a Patreon and seems to have been able to go full time on the project. It kind of seems like a simple way to pay a subscription to something that's free so that it remains free and maintained, amongst other things. There's probably other crowdfunding platforms that could work too, but I haven't really looked into it at all.

For what it's worth, I've suggested that my company look into becoming a patron for ImGui, and if you decide to do something similar, I'll be pushing for the same thing for Premake. I can't guarantee they will, but I'll constantly push for it.

**Comment by tdesveauxPKFX** [comment]
@samsinsane there is this [RELEASE.txt](https://github.com/premake/premake-core/blob/master/scripts/RELEASE.txt), not sure how up to date it is.

I'm in favor to automate releases. I can't put much time into it at the moment but would be open to split AppVeyor/Travis with someone.

As for the list Starkos shared above, maybe we should setup projects (there already is one for XCode) with the tasks required?

**Comment by starkos** [comment]
Hey guys, sorry for the delay—the RELEASE.txt is up-to-date as the last release I made (which was a while ago, I admit).

I considered a Patreon a while back and even floated the idea, but I don't know how companies would feel about funding me directly. A better idea might be to set up an [OpenCollective](https://opencollective.com) for the project itself, and then allow the core developers to draw against it?

**Comment by samsinsane** [comment]
Could always try one and see how it goes, and if it doesn't work out try the other one?

**Comment by niklas-ourmachinery** [comment]
Maybe the text on the [download web page](https://premake.github.io/download.html#v5) should be changed to better reflect reality? Currently it says that releases are made every 8 weeks, which is confusing when the last release was over a year ago. I've been waiting for 13 for a while (to fix a non-critical bug I ran into in 12) and it wasn't until today that I started to dig deeper and realized that I should probably build it myself rather than wait for 13 if I need the bug fixed.

**Comment by catb0t** [comment]
there are some FOSS alternatives to Patreon too

https://github.com/SirCmpwn/fosspay (self-hosted)

https://liberapay.com (not self-hosted)

**Comment by tdesveauxPKFX** [comment]
I attempted to create a release-5.0-alpha13 branch to prepare for a release.

If you could test the branch, that would be great. I will test it next week on my side.

If everything goes well, we could have a release in one / two weeks.

**Comment by samsinsane** [comment]
@tdesveauxPKFX GitHub says the branch is 387 commits behind master? I'm not 100% certain how @starkos made the alpha12 branch, but it looks like he started on master and then merged into the release branch?

**Comment by samsinsane** [comment]
Notes/Feedback:
- The branch appears to contain all commits from master
- `premake --version` looks correct
- `premake --help` looks correct except for the copyright ending at 2017
  - Perhaps we should have support for iOS in the `os` option?
  - The `android` value for the `os` option is at the end of the list due to how it's added, perhaps all the lists should be sorted before being displayed by `--help`?
- CHANGES.txt looks correct.
- `PRlogs_to_RELEASE_format.py` could be written in Lua instead, similar to `package.lua`. It could even extend `package.lua`?

Unrelated:
- The Premake project isn't set to be the `startproject`, which is kind of strange
- The CHANGES.txt reads very weird because it never mentions the current release by name. It says "Since 5.0-alpha12:" instead of "Changes in 5.0-alpha13:" which I think would make slightly more sense?

Nothing else jumps out at me right now, but @starkos might have some additional notes about the whole process. Also, when generating the Linux builds, try to use a distro that has glibc 2.16 so that we don't exacerbate the issue detailed in #632. Perhaps use the same distro as @starkos, whatever that happens to be?

**Comment by tdesveauxPKFX** [comment]
I opened a new issue #1173 to talk about this specific release.
