### ISSUE TITLE
Error: [string "src/base/_foundation.lua"]:137: attempt to index a nil value (local 'scope')

### ISSUE THREAD

**Issue by sl1pkn07** [premake/premake-core#1090]
Hi

With premake bfcf22b1e1020c8cabee9d406f10e3607e0a2258 and premake5 scripts from https://github.com/xenia-project/xenia project (with little tweaks for the `os.is` changes)

gets:
~~~bash
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/tmp/makepkg/sl1-xenia-git/src/xenia]|
└───╼  premake5
Error: [string "src/base/_foundation.lua"]:137: attempt to index a nil value (local 'scope')
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[/tmp/makepkg/sl1-xenia-git/src/xenia]|
~~~

but `src/base/_foundation.lua:137` show:

https://github.com/premake/premake-core/blob/bfcf22b1e1020c8cabee9d406f10e3607e0a2258/src/base/_foundation.lua#L133-L145

what happen?

greetings

**Comment by samsinsane** [comment]
I believe that error comes from `premake.override`, the `scope` isn't being found - the `scope` is the first parameter of the `premake.override` function. This is likely to occur if you've updated your version of Premake, and a function that was being overridden has moved. Your best bet is to search the repo for `.override(` and see what comes up.

**Comment by sl1pkn07** [comment]
ok, seems this is the culprit:

~~~lua
if premake.override then
  local forced_c_files = {}

  -- Forces all of the given .c and .cc files to be compiled as if they were C.
  function force_compile_as_c(files)
    for _, val in ipairs(files) do
      for _, fname in ipairs(os.matchfiles(val)) do
        table.insert(forced_c_files, path.getabsolute(fname))
      end
    end
  end

  -- for gmake
  premake.override(path, "iscfile", function(base, fname)
    if table.contains(forced_c_files, fname) then
      return true
    else
      return base(fname)
    end
  end)
  -- for msvc
  premake.override(premake.vstudio.vc2010, "additionalCompileOptions", function(base, cfg, condition)
    if cfg.abspath and table.contains(forced_c_files, cfg.abspath) then
      _p(3,'<CompileAs %s>CompileAsC</CompileAs>', condition)
    end
    return base(cfg, condition)
  end)
end
~~~

and 

~~~lua
if premake.override then
  local forced_cc_files = {}

  -- Forces all of the given .c files to be compiled as if they were C++.
  function force_compile_as_cc(files)
    for _, val in ipairs(files) do
      for _, fname in ipairs(os.matchfiles(val)) do
        table.insert(forced_cc_files, path.getabsolute(fname))
      end
    end
  end

  -- for gmake
  premake.override(path, "iscfile", function(base, fname)
    if table.contains(forced_cc_files, fname) then
      return false
    else
      return base(fname)
    end
  end)
  -- for msvc
  premake.override(premake.vstudio.vc2010, "additionalCompileOptions", function(base, cfg, condition)
    if cfg.abspath and table.contains(forced_cc_files, cfg.abspath) then
      _p(3,'<CompileAs %s>CompileAsCpp</CompileAs>', condition)
    end
    return base(cfg, condition)
  end)
end
~~~

comment this lua scripts solve the problem (with some tweaks)

so, ' src/base/_foundation.lua' is where exist the original functions and `:137:` , what mean?

**Comment by ratzlaff** [comment]
The error you are talking about in this issue is on line 137 of the scripts ***embedded*** in premake, which are in scripts.c which is created during the 'embed' action.

The 'embed' action makes the script-text smaller, but in doing so it will throw off line number reporting of exceptions thrown from the embedded scripts. 
See lines 27, 28, 29, 35, 38:
https://github.com/premake/premake-core/blob/bfcf22b1e1020c8cabee9d406f10e3607e0a2258/scripts/embed.lua#L19-L41

FWIW, I have #1040 in the PR queue specifically so that I don't have to override the premake functions (the same way you do) just to compile C files as C++

**Comment by ratzlaff** [comment]
To fix the **attempt to index a nil value (local 'scope')**, I have the following mods in my local repo:

```lua
diff --git a/src/base/_foundation.lua b/src/base/_foundation.lua
index e5d8712..a3be431 100644
--- a/src/base/_foundation.lua
+++ b/src/base/_foundation.lua
@@ -279,7 +279,13 @@
 ---
 
        function premake.override(scope, name, repl)
+               if not scope then
+                       error("unable to override '" .. name .. "'; input scope is nil", 2)
+               end
                scope, name = p.resolveAlias(scope, name)
+               if not scope then
+                       error("unable to override '" .. name .. "'; returned scope is nil", 2)
+               end
 
                local original = scope[name]
                if not original then

```

**Comment by tdesveauxPKFX** [comment]
After trying on your project, I confirm that the issue was that you need to use `require "vstudio"` before an override of function that belong to the module (here: `premake.vstudio.vc2010, "additionalCompileOptions"`).

If you don't, Premake will first interpret your `premake.lua` then load modules which means that when you are overriding, the function does not yet exists.

Also you should guard your overrides depending on the action to prevent requiring modules that are not necessary.

Something like,
```
if _ACTION:startswith("vs") then
    require("vstudio")
    premake.override(premake.vstudio.vc2010, "additionalCompileOptions", ...)
end
```

Feel free to re-open if you need more information.
