### ISSUE TITLE
Does systemversion("latest") work in vs2017?

### ISSUE THREAD

**Issue by juanPabloRamosWork** [premake/premake-core#1163]
I have been looking at this thread: https://github.com/premake/premake-core/issues/935

But when I try to add system version latest to my project like so:

    project(graphics_title)
        filter {"system:windows", "action:vs*"}
            systemversion("latest")

and then I run

$premake5.exe vs2017

And it fails because it copies and pastes "latest" into the "Windows SDK Version" when I look at the project properties. It doesn't grab the latest SDK it just write literally "latest".

Was I misunderstanding that thread? Or am I doing something else wrong?

**Comment by juanPabloRamosWork** [comment]
I am using Alpha12.

I saw that the thread was from October 2017 and read that the alpha builds got updated every 8 months and assumed that the alpha build would contain the patch.

You are most likely correct and alpha12 just doesn't contain the feature so I would need to update to a master build.

**Comment by samsinsane** [comment]
That's fair enough, alpha12 was released in August 2017 so it just missed having this feature. FWIW, our readme was updated to contain the release information using some badges. They look like this:
 [![Latest release](https://img.shields.io/github/release/premake/premake-core/all.svg)]() [![Release date of last release](https://img.shields.io/github/release-date-pre/premake/premake-core.svg)]() [![Commits since last release](https://img.shields.io/github/commits-since/premake/premake-core/v5.0.0-alpha12.svg)]()

**Comment by juanPabloRamosWork** [comment]
Thank you very much! I'll make sure to keep this in mind in the future.
