### ISSUE TITLE
Per-config file lists for gmake

### ISSUE THREAD

**Issue by Lyatus** [premake/premake-core#1185]
I'm in need of per-config file lists for my project and I was wondering if there were any plans to support it for gmake? Is it at all possible to support it for gmake? If there are no current plans and it is in fact possible, would you mind pointing me in the right direction to implement it? I'd be interested in making a pull request if I'm successful!

Also I tried looking for issues mentioning it but nothing came up, sorry if there's already an issue I missed!

**Comment by samsinsane** [comment]
The `gmake` generator was rewritten with `gmake2`, this does support file level filters and should be what you're looking for. Let me know if you have any issues!

**Comment by Lyatus** [comment]
Thanks for the quick response and sorry for the delay! I've just tried the `gmake2` action and for the most part it works great, but I discovered a bug related to per-config file lists.
If you only exclude files in a configuration but not in another:
```lua
filter {"configurations:Release"}
  excludes {"src/.../**"}
```
You'll end up with something like this at the end of the File sets section:
```makefile
ifeq ($(config),debug)
OBJECTS += ...

else
  $(error "invalid configuration $(config)")
endif
```
Which obviously fails as soon as you try to build in release. I could workaround it by excluding a dummy empty file in the release configuration:
```lua
filter {"configurations:not Release"}
  excludes {"src/dummy.cpp"}
```
This adds an `else ifeq` statement and avoids the error. I haven't looked at the code generating this part of the makefile yet, so I'm not sure if it's an easy fix but it seems to me that there's no need for such defensive code in this part of the makefile considering configuration checking has already been done at the start.

If there's anything I can do to help with this problem please tell me :)

(I hope it's fine using this issue to report this bug, or should I start another issue?)

**Comment by samsinsane** [comment]
This is very strange, I wouldn't have expected it to do that. It looks like [this](https://github.com/premake/premake-core/blob/ed483dd9bc5b5e357d210781ab2e44243c90eb5e/modules/gmake2/gmake2.lua#L234-L258) is the code responsible which looks like it was copied from [this](https://github.com/premake/premake-core/blob/ed483dd9bc5b5e357d210781ab2e44243c90eb5e/modules/gmake2/gmake2_workspace.lua#L39-L65). I don't think the `first` concept is required at all since it's generating a diff from the "global" settings? I'll try to set some time aside to look into this more and see if we can resolve the problem.

> I hope it's fine using this issue to report this bug, or should I start another issue?

Posting in this issue is fine, it's all related at the moment.

**Comment by WorldofBay** [comment]
can we just add an empty else if block in those cases as a quick fix for the release?

**Comment by samsinsane** [comment]
> can we just add an empty else if block in those cases as a quick fix for the release?

Deleting [this](https://github.com/premake/premake-core/blob/ed483dd9bc5b5e357d210781ab2e44243c90eb5e/modules/gmake2/gmake2.lua#L253-L258) would be significantly easier, I can't really see any reason to generate errors just because a configuration didn't have any custom settings. I'm fairly certain that it's just a bad copy and paste job, if you're really keen to have this fixed for alpha14, I'd be happy to review and merge a PR. Unfortunately, I've been far too busy lately to fix any issues, hopefully in the future I'll have some more time for Premake fixes.

**Comment by WorldofBay** [comment]
i'm not using gmake, so it's not a problem for me and i can't really test it without knowing anything about gmake. i just see this as a bug with a pretty easy fix.
