### ISSUE TITLE
Alpha13 generates different paths from alpha12

### ISSUE THREAD

**Issue by jakobbotsch** [premake/premake-core#1186]
In our premake file over at https://github.com/recastnavigation/recastnavigation we use the following to copy a dependency to the output directory:
```lua
postbuildcommands {
    -- Copy the SDL2 dll to the Bin folder.
    '{COPY} "%{wks.location}../../Contrib/SDL/lib/%{cfg.architecture:gsub("x86_64", "x64")}/SDL2.dll" "%{cfg.targetdir}"'
}
```

In alpha12 this generated (for vs2017):
```
IF EXIST "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll"\ (xcopy /Q /E /Y /I "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul) ELSE (xcopy /Q /Y /I "$(SolutionDir)..\..\Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul)
```

But in alpha13 it generates:
```
IF EXIST "Contrib\SDL\lib\x86\SDL2.dll"\ (xcopy /Q /E /Y /I "Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul) ELSE (xcopy /Q /Y /I "Contrib\SDL\lib\x86\SDL2.dll" "..\..\Bin" &gt; nul)
```
the latter path is incorrect and fails the build. Do we need to fix something or is this a bug?

**Comment by tdesveauxPKFX** [comment]
Well, the issue appeared because the refactor fixed an issue present in the former implementation (path starting with a folder followed with '/..' would not be normalized. ie: `build/../test` will never result in `test`).

You can temporarily get a working version changing `folderDepth` [here](https://github.com/premake/premake-core/blob/f68c386341b86e68ff3157638bd8acd499a8ae1b/src/host/path_normalize.c#L48) to `-1`.

I think the proper fix would be for normalize to detect if the path contains token (visual studio, env vars, premake) and normalize only the chunks of the path that does not contains them.

I will try to work on it this week end. In the mean time, should we have the "temp fix" on master?

**Comment by jakobbotsch** [comment]
Thank you, I have changed it to
```
postbuildcommands {
    -- Copy the SDL2 dll to the Bin folder.
    '{COPY} "%{path.getabsolute("Contrib/SDL/lib/" .. cfg.architecture:gsub("x86_64", "x64") .. "/SDL2.dll")}" "%{cfg.targetdir}"'
}
```
which works and makes more sense anyway.

By the way, just as an observation, it seems strange to me to normalize these paths in the "Lua script" form. For instance how will Premake handle an actual folder named $(abc)? Just a thought.

**Comment by samsinsane** [comment]
> By the way, just as an observation, it seems strange to me to normalize these paths in the "Lua script" form.

Yeah, I'm not a huge fan of the way we handle the command tokens and their inputs. The normalization makes sense when a token (`%{}`) is replaced with a path and not an action/system specific token. Unfortunately, Premake can be a little overzealous in manipulating the inputs and it can result in the command tokens being completely useless - I've stopped using the copy token because it was a constant battle to get a file copied across all platforms without a filter.

> For instance how will Premake handle an actual folder named $(abc)? Just a thought.

Premake *should* recognize `$(abc)` as an environment variable and leave it alone, same goes for `%abc%`. However, I would imagine it's ill-advised to name your folders like this when you're interacting with the command line, similarly, I wouldn't recommend naming your folders using the Premake token, `%{abc}`.
