### ISSUE TITLE
startproject option ignored on visual studio

### ISSUE THREAD

**Issue by WhoseTheNerd** [premake/premake-core#1227]
Title says it all.
I have workspace which contains multiple projects and only one executable project. When generating projects for visual studio 2017, The startup project is set to First projects first project dependency. 
**Any workarounds?**

**Comment by samsinsane** [comment]
It looks like after VS2017 opens a project it stores that info in the `.vs` folder beside the solution and due to this, changing the `startproject` in Premake won't have any impact. However, if you close VS2017, delete the `.vs` folder and then reopen the solution it will "detect" the change in project order.

**Comment by WhoseTheNerd** [comment]
Thank you, didn't except startup project to be stored  in the `.vs` folder.
