### ISSUE TITLE
Issues with premake-android

### ISSUE THREAD

**Issue by ifarbod** [premake/premake-core#1251]
I've been using the official `android` module way before it made its way to premake-core, I already got sick of gradle/CMake/ninja at the time but thankfully this extension was a lifesaver, it's nice to have everything in one IDE.
Having used it for more than a year, I came along with many issues that I had to manually fix and work around, eventually, I switched to managing manual VS solutions for this sole reason. In fact I only do so for Android and iOS while everything else (win32/macos) is covered by premake.
After I saw it getting merged into upstream `premake-core`, I've noticed that it has received some fixes, So I started to switch back slowly. While it's more stable than ever, it's far enough to be feature complete. Here's a short list of my current issues and concerns:

- [x] Rework the `stl` API, have `staticruntime` to decide instead. Example:
```lua
stl "libc++"
staticruntime "On"
-- Would produce: "c++_static"
-- Or:
stl "gnustl"
staticruntime "Off"
-- Would produce: "gnustl_shared"
```
- [x] The `MultiProcessorCompilation` flag has no effect. This is because Android MDD projects use `UseMultiToolTask` instead.
- [x] The `kind` value for packaging projects `androidproj` doesn't really feel inline with the built-in ones like `SharedLib`, `ConsoleApp` and such, my suggestion would be to change it to something like `AndroidApp`, `Packaging` or `WindowedApp` if it's guaranteed to not conflict with anything.
- [x] Some of the windows/VS-specific attributes can easily end up in Android projects if you use them at the workspace scope, ex: `characterset "Unicode"`
- [ ] A simple way to change the Ant build target, so compiling signed APKs becomes possible. `signapk "On"`, I don't know of a better name for this.
- [ ] `toolchainversion`'s functionality could be merged with `toolset`, maybe something like `toolset "clang-5"`
- [x] `thumbmode` only works for the old vs-android extension, also could change its name to `instructionmode`.
- [x] A lot of the well-established premake APIs don't have any effect in VSAndroid, examples include but not limited to: `disablewarnings`, `pic`, `vectorextensions`, `rtti`, `exceptionhandling`.
- [x] `exceptionhandler "UnwindTables"`
- [x] The value `C++latest` for `cppdialect` should generate a `-std=c++1z`, Meanwhile `C++17` generates `AdditionalBuildOptions` instead of `CppLanguageStandard`. `cdialect` simply doesn't work.
- [ ] ~~Add linker and librarian settings to `flags`.~~ They should be added as new functions or implementation of existing ones.
- [x] TargetName doesn't work in .androidproj. It used `Application` as default.
- [ ] IntelliSense doesn't work for Java files (could be because of IntDir)
`Cannot determine the project containing the file x.java`
- [x] Unmerged PR #1112 .
- [x] ~~Drop support for VS2015 and the vs-android extension to make future maintenance easier.~~

(I'll try to keep this list up-to-date)

I'm already trying to do some of these [here](https://github.com/ifarbod/premake-core/tree/android-changes) and I'm willing to send PRs, But I would like to hear the maintainers' opinion before taking any big decisions.

**Comment by samsinsane** [comment]
> The kind value for packaging projects `androidproj` doesn't really feel inline with the built-in ones like `SharedLib`, `ConsoleApp` and such, my suggestion would be to change it to something like `AndroidApp`, `Packaging` or `WindowedApp` if it's guaranteed to not conflict with anything.

Yeah, that's my fault really. I'm not really sure what would be a good solution. I think `AndroidApp` would be too specific but it's kind of unique to Android, so I'm not sure. I like the idea of `Packaging` but not sure what else could use it. `WindowedApp` makes some sense, but it's not quite right, however mimicking what iOS and macOS do for their App bundles might be the way to go?

> `toolchainversion`'s functionality could be merged with `toolset`, maybe something like `toolset "clang-5"`

To be frank, I detest the `toolchainversion` API - it forces entire Premake updates or Premake hacks to support new versions which is just stupid given it's literally just a couple of numbers. I'm not really sure if we should merge them either, it starts to imply that we handle that outside of Android - which we don't.

> Add linker and librarian settings to `flags`.

If you're talking about the API `flags`, create new APIs instead because we're not adding to `flags` anymore.

> TargetName doesn't work in .androidproj. It used `Application` as default.

Sorry about that!

> Drop support for VS2015 and the vs-android extension to make future maintenance easier.

I disagree with this. People use older versions of VS and we shouldn't just arbitrarily cut them off, we've been able to support multiple versions of VS in the `vcxproj` generator, I can't see any reason why we can't do it here too. If you don't know if it works in VS2015, don't change what VS2015 does and the same goes for vs-android.

**Comment by starkos** [comment]
> The kind value for packaging projects `androidproj` doesn't really feel inline with the built-in ones like `SharedLib`, `ConsoleApp` and such, my suggestion would be to change it to something like `AndroidApp`, `Packaging` or `WindowedApp` if it's guaranteed to not conflict with anything.

I don't remember…was there a reason we didn't do it like:

```lua
kind 'ConsoleApp'
system 'Android'
```

…?

**Comment by ifarbod** [comment]
Thank you guys for your responses.

> Yeah, that's my fault really. I'm not really sure what would be a good solution. I think AndroidApp would be too specific but it's kind of unique to Android, so I'm not sure. I like the idea of Packaging but not sure what else could use it. WindowedApp makes some sense, but it's not quite right, however mimicking what iOS and macOS do for their App bundles might be the way to go?

All right, I went with `Packaging` for now.

> To be frank, I detest the toolchainversion API - it forces entire Premake updates or Premake hacks to support new versions which is just stupid given it's literally just a couple of numbers. I'm not really sure if we should merge them either, it starts to imply that we handle that outside of Android - which we don't.

I don't have any ideas on what would be the most optimal way of doing this, but after seeing your review on that android fixes' PR by @TurkeyMan I think it'd make sense to have a list of the valid toolchain version for a certain version of VS and throw a warning if using something outside of that list.

> If you're talking about the API flags, create new APIs instead because we're not adding to flags anymore.

Noted. Will do them as soon as I find some time.

> Sorry about that!

No worries, it's already fixed in [my fork](https://github.com/ifarbod/premake-core/commit/2a912a5fa8abb2d6539fb3f984cef719788943ba). :)

> I disagree with this. [snip]

Right, won't argue on this one, that's why I've made an issue before making a PR anyway.

@starkos 

I usually invoke premake for android projects like this:
```sh
premake5 --os=android vs2017
```

But I've seen some folks define a new option and set `system` based on that.

**Comment by samsinsane** [comment]
@starkos The only issue with mapping existing kinds to this project type is that existing projects won't build correctly, mapping `ConsoleApp` and `WindowedApp` to `SharedLib` would result in the whole project building correctly for Android but without an APK. If `*App` generated the AndroidProj project, I'm pretty sure it would fail unless the user had the other required files ready to go, and if they did it would likely just generate an APK that contains all of the apps dependencies but wouldn't run because the "actual program" would be missing.

If I didn't make any sense with the above, the simplest way to explain it would be:
`.vcxproj` = `.c` + `.cpp` -> `.so`
`.androidproj` = `.so` + `.java` -> `.apk`

`.androidproj` is really just a fancy `kind "Utility"` that calls Ant/Gradle. It contains Java files too, but I don't know if it compiles them directly or not (I'm pretty sure it's part of Ant/Gradle) and I don't recall it having Intellisense on the files either.

I'm not super opposed to what you're suggesting, it just requires that users have the below on all of their existing `*App` projects to just get it to build their project normally (with the Android toolchain):
```lua
filter { "system:android" }
  kind "SharedLib"
filter {}
```

---

@ifarbod I forgot to mention, try to open multiple PRs instead of just a single giant PR. PRs often get stuck due to parts needing more work, and it would be a shame to have support for new or existing APIs be held up because of other unrelated changes. I'll let you judge how many existing APIs to have in a single PR, but I think new APIs are probably best to have in their own PRs just in case there's issues or an existing API could be used instead. :+1:

**Comment by ifarbod** [comment]
@samsinsane Right, should I do this for the minor fixes as well or only the new APIs that I'm going to add?
Also, I probably forgot to mention unit tests, can I do them in another PR later? Because my current focus is just to get everything to work together :)

**Comment by starkos** [comment]
@samsinsane That's not entirely unlike WindowedApp/macOS, where you need to provide an `Info.plist` before anything will run.

I've done very little Android development, and all on C#/Xamarin, so I'll defer to the folks with more experience on this one. Just pointing out some similar use cases in case they're helpful.

If you _did_ decide to take the *App/Android approach, perhaps some validation logic could be added to make sure all of the required resources are present? Not sure if that's feasible.

**Comment by samsinsane** [comment]
@ifarbod It kind of depends on the minor fixes, but you can probably group a few of them together. It's up to you there. As for unit tests, it would be good if they were in the PRs too, ensuring that things continue to work is important.

@starkos Here's a screenshot of the properties list for the `.androidproj` format:
![image](https://user-images.githubusercontent.com/11887457/54000235-65c5c000-4192-11e9-8d4d-254affea0130.png)
It's not quite like the macOS project, the macOS project still contains source code and it is compiled by that project. For Android, this project doesn't compile anything it just calls Ant and doesn't really do anything else. This is why I don't quite agree with mapping the existing kinds to this project, it would require projects to change their configuration to just compile the source code. The APK project will always need to be an extra project rather than an extension of an existing one.

Having said this, I guess we could generate two project files from a single Premake `project` when the user specifies `*App` for Android. One being the expected source code compiling project, `.vcxproj`, and the other being the APK generating project, `.androidproj`. This would make it easier to map APK generation to other actions/implementations, and would reduce the amount of configuration required to generate the APK. Thoughts?

**Comment by starkos** [comment]
@samsinsane That sounds like a good approach to me, should make sense to anyone familiar with Android development.

**Comment by ifarbod** [comment]
All right, I think I finally found some time to do this during this week, multiple PRs incoming.

**Comment by ifarbod** [comment]
I might add `hidesymbols` On/Off for `-fvisibility=hidden` in buildoptions, thoughts?

**Comment by samsinsane** [comment]
I'm fairly certain that we already have something that does `-fvisibility=hidden`? I could very easily be mistaken.

**Comment by ifarbod** [comment]
@samsinsane you're right, there's the `visibility "Hidden"` API.

**Comment by redorav** [comment]
I wanted to make a quick comment on this bug. Since the change to specify the androidproj as packaging, the project no longer does automatic deployment if the code is out of date when pressing f5 to debug. Instead it compiles but runs the previous build on the device. Is this something you're aware of?

**Comment by ifarbod** [comment]
@redorav That's likely a VS bug.

**Comment by samsinsane** [comment]
@ifarbod What else needs to be done to close this issue? If there's a number of items left, perhaps a checklist (`[ ] item` instead of `- item`) would be the best way forward?

**Comment by ifarbod** [comment]
Sure, I don't think there's any tasks left.
