### ISSUE TITLE
When will there be a new release with VS2019 support?

### ISSUE THREAD

**Issue by amc522** [premake/premake-core#1277]
Just curious. No rush. Easier to get the released builds instead of building from master.

**Comment by samsinsane** [comment]
There's currently an open issue for the next release, #1213. However, given the time that has elapsed since the process started, the process is likely to start again with a more recent branch. You can track the status of the release with that issue, I believe we'll be creating issues for all future releases and they'll have the `release` label too.

**Comment by amc522** [comment]
Thanks for the info! I'll track that issue.
