### ISSUE TITLE
What is the use of _x function?

### ISSUE THREAD

**Issue by hanseul1795** [premake/premake-core#1379]
from the source code, I see that the user can adjust `indentLeve`l by using _p function (like `push` and `pop` functions)

but I'm little confused about the use of `_x` function.

**Comment by samsinsane** [comment]
`_x` will call `premake.esc` which will call the currently set escape function. For example, imagine Premake generates the following XML document:
```xml
<xml>
  <userinput>
    CustomData
  </userinput>
</xml>
```
The user added `CustomData` using `userinput "CustomData"`, but what if the user wanted to add in `</userinput>` instead? That would break the XML file:
```xml
<xml>
  <userinput>
    </userinput>
  </userinput> <!-- This is now a duplicate close -->
</xml>
```
If instead of using `_p` to emit the value of `userinput`, if we use `_x` it will look like this:
```xml
<xml>
  <userinput>
    &lt;/userinput&gt;
  </userinput> <!-- This is no longer a duplicate close -->
</xml>
```

From memory these two functions are deprecated in favour of `premake.w` and `premake.x` I think?
