### ISSUE TITLE
overrides are not conditional after a filter.

### ISSUE THREAD

**Issue by stolk** [premake/premake-core#1387]
If I apply a filter, and then do a **premake.override** then the override is done always, not just when the filter matches.

Is this by design?

**Comment by samsinsane** [comment]
This is by design, `filter` only applies to the APIs (created with `premake.api.register`) - they're not normal functions like `premake.override`, in very basic terms, they just store whatever you specify in a big table for usage later. Generally, when using `premake.override` you'll have access to a `wks`, `prj` or `cfg`, these are what the big table is used to populate.

**Comment by starkos** [comment]
@stolk—You can see a list of these project scripting APIs on the [Project API](https://github.com/premake/premake-core/wiki/Project-API) of the wiki, or [_premake_init.lua](https://github.com/premake/premake-core/blob/master/src/_premake_init.lua) in the source code (which is likely more up to date). Feel free to comment here with questions.
