### ISSUE TITLE
library extension when linking against system lib (on new platforms.)

### ISSUE THREAD

**Issue by stolk** [premake/premake-core#1388]
**What's your question?**

How is the library extension determined when generating library dependencies?

**Details**

From the manual:

_When linking against system libraries, do not include any prefix or file extension. Premake will use the appropriate naming conventions for the current platform._

I am adding support for a new platform (handheld gameconsole) to premake, and this platform uses **.a** for library names.

I've set up the new OS types as a POSIX OS, and it mostly works.

But when I add `links( {"fmod"} )` then the generated visual studio file will create an additional dependency called **libfmod.lib** and not **libfmod.a** unfortunately.

NOTE: for the dependency projects in my application, it does use the .a suffix, and correctly links against it. It is just an issue with 3rd party pre-built library.

I looked in the premake5 sourcecode, but am not sure where this library suffix is determined. The suffix stuff defaults to posix, which I've set, so I'm puzzled.

**Comment by samsinsane** [comment]
Unfortunately, this is kind of tricky to provide accurate feedback without the code - which I understand you can't provide due to the strict NDAs that consoles tend to have. So, it may take awhile to provide help in narrowing this problem down, but I think I have a good idea based on what you've said so far.

> But when I add `links( {"fmod"} )` then the generated visual studio file will create an additional dependency called `libfmod.lib` and not `libfmod.a` unfortunately.

This is quite strange, both the `lib` prefix and the `.lib` extension is very strange. I can't recall off the top of my head where this issue is, [this](https://github.com/premake/premake-core/blob/63a1e5ff3b66ef97392f42a8df7da91fc863ecf4/modules/vstudio/vs2010_vcxproj.lua#L1368) function outputs the `links` entries, have you defined a new toolset for this platform and set that as the default when on this platform? This function will call `vstudio.getlinks` which calls `msc.getlinks` which will add the `.lib` extension, seen [here](https://github.com/premake/premake-core/blob/63a1e5ff3b66ef97392f42a8df7da91fc863ecf4/src/tools/msc.lua#L311-L332). When the toolset is set it calls that toolsets `getlinks`, for example the `gcc.getlinks` won't add the prefix or extension, as seen [here](https://github.com/premake/premake-core/blob/63a1e5ff3b66ef97392f42a8df7da91fc863ecf4/src/tools/gcc.lua#L450-L515).

**Comment by stolk** [comment]
Thanks.
What I did:

* Added a new architecture to vstudio.lua vstudio.vs2010_architectures[]
* Added a new allowed os option in _premake_init.lua
* Added these two to _foundation_lua
* Added the posix tag for the os in os.lua

Everything else, I do with the premake override system.

I see that in my case the toolset's getlinks is called, and this will use the lib prefix and postfix. Not sure which toolset it is, if I print it, it just says table.

**Comment by samsinsane** [comment]
> Not sure which toolset it is, if I print it, it just says table.

I would say that it's `msc`, you can compare the table with `premake.tools.msc`. If you need to create a new toolset that's similar to `msc` or `gcc`, I recommend looking at [`clang`](https://github.com/premake/premake-core/blob/master/src/tools/clang.lua) which is just copying GCC and making some modifications. I assume you're going to want to use GCC/Clang regardless.

**Comment by stolk** [comment]
I fixed my issue by changing tools/msc.lua to recognize .a as a library, which stops it from appending .lib to it.
```
        function msc.getLibraryExtensions()
                return {
                        ["lib"] = true,
                        ["obj"] = true,
                        ["a"]   = true,
                }
        end
```

**Comment by samsinsane** [comment]
Closing based on previous comment.
