### ISSUE TITLE
Can't add custom build rule to gmake2 (Linux)

### ISSUE THREAD

**Issue by q4a** [premake/premake-core#1398]
**What are you trying to do?**
I'm trying to add custom build rule to gmake2 (Linux) with Premake v5.0.0-alpha14 ([last commit also tested](https://github.com/premake/premake-core/tree/a640f86d5b6514a269f13ec3698e650bd953a282)).

**What problem are you having?**
On Windows my script adds custom build rule. There is call of `C:\Qt\5.14.0\msvc2017_64/bin/moc`:
https://ci.appveyor.com/project/q4a/ps4delta/builds/30674575/job/bowaalmkws2eg4gj#L199
But don't adding on Linux. There is no call of `/usr/bin/moc`:
https://ci.appveyor.com/project/q4a/ps4delta/builds/30674575/job/o75820tvxxki5h64#L453

**What have you tried so far?**
I already build [lastest premake](https://github.com/premake/premake-core/tree/a640f86d5b6514a269f13ec3698e650bd953a282) from source, but problem still here.

Also I added 2 prints to `addMOCCustomBuildRule ` in premake-qt:
https://github.com/q4a/ps4delta/blob/f9c30bce929c767ffebc3d00246177f75bca099e/tools/premake/premake-qt/qt.lua#L621

And got good custom commands on Windows:
https://ci.appveyor.com/project/q4a/ps4delta/builds/30674575/job/bowaalmkws2eg4gj#L24
And Linux:
https://ci.appveyor.com/project/q4a/ps4delta/builds/30674575/job/o75820tvxxki5h64#L413

**What version of Premake are you using?**
Tested:
> $ premake5 --version
> premake5 (Premake Build Script Generator) 5.0.0-alpha14

And this version:
https://github.com/premake/premake-core/tree/a640f86d5b6514a269f13ec3698e650bd953a282

**Anything else we should know?**
I'm using copy of [premake-qt](https://github.com/dcourtois/premake-qt) and it is 2 years old, but still works on Windows fine. May be something Linux/gmake2 related was chaned.

**Comment by samsinsane** [comment]
It would have been helpful if you linked to/from dcourtois/premake-qt#15 so that everyone is aware of what has been done to triage this.

**Comment by dcourtois** [comment]
Oh, thanks for linking it (didn't even notice that an issue was opened here since I didn't have any news from @q4a on the original issue in my repo)
I'm a bit rusty and didn't spend too much time on the issue, but let me know if you need some info. My guess is that it has to do with the fact that the custom command outputs a header file (the other custom commands all generate compilation units, and those work correctly) but I couldn't figure out why it behaves like this.

**Comment by q4a** [comment]
I tried to remove `shadowContext ` from here: 
https://github.com/premake/premake-core/blob/0a9844891d5cd562181bbad2dbc34daf65b7c3cc/modules/gmake2/gmake2_cpp.lua#L178
And then add double quote here:
https://github.com/dcourtois/premake-qt/blob/0ddc49715c7892211774d4b5e705a7c5559aeed4/qt.lua#L623

(because makefiles has lines like `echo Moc'ing MyFile` instead of `echo "Moc'ing MyFile"`).

After that I get wiered double bug and go to vacation. I'll be away from my main PC untill next week, but and then I can try to show my patch for `modules/gmake2/gmake2_cpp.lua` and try to find my mistake in it.

**Comment by dcourtois** [comment]
Hi there,

I just wanted to give a small update on this issue: it's an issue with my addon. gmake2 correctly handles custom commands on header files, the bug described here only applied to custom commands added by my addon (premake-qt) I still couldn't figure out why, but working on it.

Someone can probably close this issue since you *can* actually create custom commands in the gmake2 action.

**Comment by samsinsane** [comment]
@dcourtois Thanks for the update, I'll close the issue based on your feedback here.
