### ISSUE TITLE
QtCreator support

### ISSUE THREAD

**Issue by abique** [premake/premake-core#140]
Hi,

It would be awesome to have QtCreator support right?

Cheers,
Alex

**Comment by starkos** [comment]
You might want to open a ticket [here](https://github.com/dcourtois/premake-qt).

**Comment by lucianolorenti** [comment]
After fighting with qmake project's file. I've switch my implementation to use [qbs](https://wiki.qt.io/Qt_Build_Suite). Qt Creator supports qbs since the last few versions. The [premake-qbs](https://github.com/lucianolorenti/premake-qbs) is far from perfection, but works for me.

It's for premake 5

Maybe it can serve as a starting point for someone who wants to develop the module in a more appropriate form.

**Comment by abique** [comment]
There is also an option to generate a generic project right?

**Comment by samsinsane** [comment]
Closing this issue, it looks like there's two modules that can or could handle this functionality.

**Comment by starkos** [comment]
For the curious, there is currently [a Qt add-on listed on the Modules page](https://github.com/premake/premake-core/wiki/Modules) of the wiki.
