### ISSUE TITLE
Feature: Expand tokens in plain lua functions

### ISSUE THREAD

**Issue by xahon** [premake/premake-core#1436]
Solving my original issue https://github.com/premake/premake-core/issues/1435 i stucked into problem with tokens expansion. Tokens are expanded correctly in expressions like that:  
```LUA
project "ProjectA"
    kind "StaticLib"
    prebuildcommands {
        "{ECHO} %{prj.name}",
        print("%{prj.name}"),
    }
```

I expect next output:
> ProjectA
> ProjectA
However i get:
> ProjectA
> %{prj.name}

and `print` command gets evaluated at solution generation time:
> C:\dev\sample_project>call Tools\premake5.exe vs2019
> %{prj.name}
> Building configurations...
> Running action 'vs2019'...
> Generated ProjectA.vcxproj...
> Done (63ms).

there is an ugly workaround to wrap a lot of calls into the string like that:
```LUA
prebuildcommands {
  "lua -e \"dofile([[%{prj.location}functions.lua]]); CallMyFunction(%{prj.name})\"",
}
```
it works, but looks ugly

**Comment by samsinsane** [comment]
I'm going to close this, the tokens can't be expanded in plain Lua functions because it doesn't make any sense. Consider a simple example like this:
```lua
project "A"
  prebuildcommands { "{ECHO} %{ cfg.buildcfg }" }
```
When you run this in VS, you'll see `Debug` in your debug builds, and `Release` in your release builds. If you replace `prebuildcommands` with any plain Lua function, what happens? You've only called it once, but there's a number of potential values that could be passed in. Additionally, our tokens aren't evaluated immediately, they're evaluated after your script has finished executing.

Depending on your requirements something like this might be better:
```lua
function MyFunction(projName)
  return "{ECHO} " . projName
end

project "A"
  prebuildcommands { "%{MyFunction(prj.name)}" }
```

**Comment by starkos** [comment]
Premake executes in stages: first it runs your script and collects all of the information about your project, then it runs a preprocessing pass over that information to get it ready for use, and then it runs your selected action to generate the project files. Tokens are not evaluated until that last stage, because that's the only time we have all of the required information, like: what's the build configuration? What system is being targeted? What's the current source file we're targeting?

If tokens could be expanded at script execution time…well, then we wouldn't need tokens, you'd just reference the variables directly.

Hope that helps a little, feel free to keep asking questions if you're confused.
