### ISSUE TITLE
Changing $(SolutionDir) / include directories in external project.

### ISSUE THREAD

**Issue by tomxmm0** [premake/premake-core#1448]
**What are you trying to do?**
Include an external project in my own premake project.

**What problem are you having?**
The external project uses $(SolutionDir) for include directories, the problem is that it gets overwritten to my premake solution dir instead of the external project's solution dir and it creates invalid paths.

**What have you tried so far?**
I tried to overwrite the includedirs inside the external project to my own directories but that didn't do anything.

**What version of Premake are you using?**
5.0.0-alpha14

**Anything else we should know?**
I know that I could just change the include directories inside the external project solution, but I use git submodules so that isn't really ideal, so I'm trying to look for a premake fix instead.

Project code for reference:
```lua
    externalproject "raylib"
        location (path.join(raylib.project, "raylib"))
        uuid "8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942"
        kind "SharedLib"
        language "C"

        defines {
            "BUILD_LIBTYPE_SHARED"
        }
```

**Comment by samsinsane** [comment]
Unfortunately, I don't think there's any way to do what you're wanting. Premake doesn't modify any `externalproject`, so your usage of `defines` above won't work either. There's a few options that I can think of:
1. Have Premake recreate the project, so you'd have to define a full `project` instead of just an `externalproject`. (This is what I do for our dependencies we opt to build from scratch at work)
2. Use Lua to load and modify those projects when the project is being regenerated.
3. Fork the dependency and maintain a branch that you either rebase onto latest or merge with latest, and make your modifications to the project files that way. 
4. Copy the project files into your repo and either modify them to work from a different location, or modify them to work from the location they should be in and use Lua to copy your modified files over the top.

**Comment by starkos** [comment]
Per @samsinsane's suggestion (2.): the Lua runtime Premake is built on has general-purpose [file I/O and string libraries](https://www.lua.org/pil/contents.html#P3), so you could in theory drop some code into your `premake5.lua` to rewrite the 3rd party project to replace the `$(SolutionDir)`.

Or, another option would be to submit a PR to the 3rd party project to make the include paths project-relative instead of solution-relative. It sounds like you have a good use case for it that they maybe hadn't considered.

I'm going to mark this closed as answered, but feel free to continue the conversation if you still have questions.
