### ISSUE TITLE
Recursive FILES don't follow symbolic links on Linux

### ISSUE THREAD

**Issue by jendo42** [premake/premake-core#1459]
**Environment**
premake5 (Premake Build Script Generator) 5.0.0-alpha15
Kernel:  4.4.0-18362-Microsoft x86_64 GNU/Linux

**What have I observed**
In filesystem I got among the other things file:
`./src/tool-rescom/external/pugixml/pugixml.cpp`

The `pugixml` directory is _symbolic link_.
In my project I using for loading the file following line:
`
files {
		"./src/%{prj.name}/**.cpp",
}
`

Found that when I generate _gmake_ or _gmake2_ workspace, the `pugixml.cpp` file is ignored and not included in the final make script.

When I specified "full path" to the file, then it starts to work:
`
files {
		"./src/%{prj.name}/external/pugixml/pugixml.cpp",
}
`

**Comment by starkos** [comment]
At a guess, that fix would probably have to made in [the Posix version of `os_matchisfile()`](https://github.com/premake/premake-core/blob/master/src/host/os_match.c#L160-L179), but at a quick glance I'm not sure why symlinks are being missed.

**Comment by samsinsane** [comment]
I would say it's probably this:
https://github.com/premake/premake-core/blob/5bb0bef41cadc19497767180ec27cf74e2604ad4/src/host/os_match.c#L164-L168

`DT_LNK` is a symbolic link, we don't handle it explicitly and we probably need to - I would say all folders that are symbolic links are being marked as files because `== DT_DIR` will fail as it will also have `DT_LNK`, or it will have that instead? I would expect it to be `DT_DIR | DT_LNK` but the docs for `readdir` didn't seem to indicate either way. I would say it's most likely as simple as changing the `== DT_DIR` to `& DT_DIR`?
