### ISSUE TITLE
c++ project alongside with c# build fails

### ISSUE THREAD

**Issue by zulis** [premake/premake-core#1495]
If premake5 file contains only c++ project then c++ project builds. As soon as I add c# and regenerating with premake, c++ fails on build with error. Error says that c++ project has not reference to .NETFramework. This c++ project is **not managed** c++ project. What am I doing wrong? Using vs2019
```
1>------ Build started: Project: glfw_shared, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\NuGet\16.0\Microsoft.NuGet.targets(186,5): error : Your project does not reference ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.
1>Done building project "glfw_shared.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

c++ build fails after adding this:
```
project "csharp_hello_world"
	kind "ConsoleApp"
	language "C#"
	clr "Unsafe"
	nuget { "glfw-net:3.3.1" }
	
	files
	{
		path.join(BGFX_DIR, "bindings/cs/**.cs"),
		"examples/%{prj.name}/**.cs"
	}

	links { "System.Drawing" }

	filter "configurations:Debug"
		symbols "On"
		optimize "Debug"
		defines "DEBUG"

	filter "configurations:Release"
		optimize "Full"
```

**Comment by tritao** [comment]
The error is probably related to the `nuget` directive, maybe try changing the targeted .NET framework with the `netframework` directive.

FYI we've been using Premake with hybrid C++ and C# projects for years, under all platforms and everything works great, though we do not use the `nuget` support in Premake yet.

**Comment by zulis** [comment]
Unfortunately without nuget and with defined netframework result the same - error.

**Comment by samsinsane** [comment]
The error is with a different project, are you able to provide the full Premake script? Or a minimal repro case if the full script can't be shared.

**Comment by zulis** [comment]
Sure, made it public https://github.com/zulis/test-bgfx

**Comment by samsinsane** [comment]
This is really strange - the C# project doesn't build when `dotnetframework "netcoreapp3.1"` is specified (probably because I don't have that version installed?), it also includes a whole bunch of random files in the build folder, but there's nothing in the csproj that indicates why this happens.

As for the errors, it looks like it's because you're dumping all of the projects into the same location. I'm guessing this is some weird limitation of VS, the `csharp_hello_world` project creates a bunch of nuget files in `build\vs2019\obj` which the vcxproj files automatically pick up regardless of their configurations - changing their `objdir` has no impact on the auto-detection of these nuget files. Some of them might build initially, but then they'll all fail once the C# project has created the nuget files.

I was able to get around this by putting the C# project into its own folder, but it's probably easier to change the `location` call to `location(BUILD_DIR .. "/%{prj and prj.name or ''}")`.

**Comment by zulis** [comment]
Location change helped. Thanks @samsinsane

**Comment by samsinsane** [comment]
@zulis I had the project being skipped too - I think it was skipping for me because the .NET version wasn't installed on my machine, this could be the same problem for you?

**Comment by zulis** [comment]
@samsinsane .NET Core is installed on my machine. VS would shout on project opening if required .NET version would not be available.

**Comment by samsinsane** [comment]
@zulis I've had a quick look at the premake5.lua again, I think I might have commented out the CLR and .NET version lines? Sorry, I really don't recall what caused it - there's something that causes VS to flag it as skippable, I believe the Premake output doesn't flag it as skippable.

**Comment by zulis** [comment]
@samsinsane Resolved by adding "Any CPU" plus some workaround [https://github.com/zulis/test-bgfx/commit/5ecfcbe9e3badc3ec26b9bb84cfeb51adc56f45e](https://github.com/zulis/test-bgfx/commit/5ecfcbe9e3badc3ec26b9bb84cfeb51adc56f45e)

**Comment by samsinsane** [comment]
@zulis Strange, I don't recall doing anything like that, I'm glad you figured it out though! If you haven't already, you may want to check out `configmap` for that.
