### ISSUE TITLE
cannot rename pdb filename.

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#151]
I change my premake4 to premake5. but today I find premake5 didn't rename pdb filename. I need pdb file. I search the code. I find you leave an functon. I try to fork my respository, modify the
```Lua
	function m.programDataBaseFileName(cfg, toolset)
		if toolset then
			p.w('ProgramDataBaseFileName=""')
		end
	end
```
but it doesn't work. and I don't know how modify code as your wish.
So, Please add these codes. Thx.

**Comment by starkos** [comment]
I don't have enough information to go on here. Can you provide a sample script that shows what you're trying to do, and what didn't work? Thanks!

**Comment by leeonix** [comment]
I try to modify like `m.outputFile(cfg)
```
	function m.programDatabaseFile(cfg, toolset)
		p.x('ProgramDatabaseFile="$(OutDir)\\%s.pdb"', cfg.buildtarget.basename)
--		if toolset then
--			p.w('ProgramDatabaseFile=""')
--		end
	end
```
rebuild premake5.exe
it doesn't work. it cannot rename the pdb file name. same project generate

**Comment by starkos** [comment]
> premake5 didn't rename the pdb filename

What PDB file name did you get? What PDB file name did you expect? Can you provide a sample project script (that is, a premake5.lua) that reproduces the problem you're seeing?

**Comment by leeonix** [comment]
In premake4. PDB file name, same as output name. this code from premake 4.4.2.
```Lua
_p(4,'ProgramDataBaseFileName="$(OutDir)\\%s.pdb"', path.getbasename(cfg.buildtarget.name))
```
for example, if my lua library is `lua_static.lib`, pdb file is `lua_static.pdb` and pdb file path also in output path
but in premake5 pdb file is default name `vc100.pdb` and in obj file output path.
I don't know why you remove this code.

**Comment by starkos** [comment]
Thank you, that helps, I get it now.

I would like Premake to generate files that match the defaults for each tool. So the default Visual Studio project you get from Premake is the same as what you get from choosing File > New Project… in Visual Studio, or as close as we can get it. The PDF file name wasn't the same as that default, so that is why it was changed.

I will revisit it though. Let me generate some projects out of Visual Studio and see what it does again. Why do you want to change it, out of curiosity? Are you having conflicts between projects?

**Comment by leeonix** [comment]
link windows's exe file or dll file. the `pdb` file name will write in it.
I use minidump using `pdb` file is important to detect deeply bug.
In our test environment maybe test 10000 times, anything is normal.
but in client's computer, maybe 10 second appear one bug. especially memory bug. `Access Violation` display.
so I will publish my `.exe` with `.pdb` file in same dir. `minidump` will use `.pdb` file and create has source line number's `.dmp` file. without `.pdb` file, it only has memory address.
minidump use `.pdb` file name to focus which pdb file. not many same name `vc100.pdb`

why I like premake? I change one place, other place going to change. Visual Studio has two or  more configuration. have four or more configuration? I flip out. if rename default output dir name, output file name, any other config property. I need choose on configuration to change them all. but sometimes I'll forget to choose configuration page. bug appear, and I find and find again, problem is I forget choose configuration page. that make me nervous.

**Comment by leeonix** [comment]
I think if has
```Lua
        flags { 'Symbols' }
```
the `pdb` file need output in `targetdir`.
because many programmer using visual studio doesn't know it.

**Comment by starkos** [comment]
As far as this:

> I try to modify like `m.outputFile(cfg)
> it doesn't work. it cannot rename the pdb file name. same project generate

You may have been modifying the wrong one. I think you should be editing this one in `src/actions/vstudio/vs2010_vcxproj.lua`:

```lua
	function m.programDataBaseFileName(cfg)
		-- just a placeholder for overriding; will use the default VS name
	end
```

**Comment by starkos** [comment]
I've been asked to revisit this and to figure out why this change was necessary.

I manually generated a bunch of projects through the UI, for various versions of Visual Studio. The default Program Database File Name is, indeed, `$(IntDir)vc$(PlatformToolsetVersion).pdb`. However, on every build I tried this file is also copied to `$(TargetDir)/$(TargetName).pdb`, and this happens without automatically, without the addition of a `<ProgramDataBaseFileName>` element.

Since it appears in my testing that we get the desired behavior without the need for this element, I'm inclined to roll back #162 and allow Visual Studio to use its default behavior again. Can you provide any more information on why you felt you needed to change it? Is minidump not able to use the PDB file that is already in the target directory?

**Comment by rxantos** [comment]
I also need to be able to specify the location of the pdb file. For static libraries, so I can create one with the same name and in the same directory that the static library is. (which is a different directory). 

The compiler does not that on its own (at least Visual Studio 2013) and instead just creates  the one in the obj directory (vs120.pdb). Which means that if its moved or deleted the debug information is lost. Of course it does create the secondary pdb in the case of a DLL or an executable. But not for static libraries.

I tried with linkoptions {"-PDB:MyLib.pdb"}  but it requires the precise path, no macros.

**Comment by rxantos** [comment]
After some reading (and just in case someone else have the same problem with static libraries).

```
-- Change the resulting pdb file.
premake.override(premake.vstudio.vc2010, "programDataBaseFileName", function(base, cfg)
	if cfg.debugformat ~= "c7" and cfg.flags.Symbols then
		local filename = cfg.buildtarget.basename
		premake.w('<ProgramDataBaseFileName>$(OutDir)%s.pdb</ProgramDataBaseFileName>', filename)
	end
end)
```
At the begining of the premake5.lua to get back the old behaviour

**Comment by tapika** [comment]
I had this problem of .exe having exactly same filename as dll, ending up into same directly. By the time when I've realized that two projects are conflicting with each other - both .dll's were already in setup package and change was not trivial to revert from everywhere.

So I've ended up overriding .pdb filename, but unfortunately not only compiler flag needs to be changed but linker as well.

So override currently looks like this in my own lua script:
`    --
    -- Change resulting .pdb file from compiler and linker configuration.
    --
    premake.override(premake.vstudio.vc2010, "programDataBaseFileName", function(base, cfg)
        if cfg.debugformat ~= "c7" and cfg.flags.Symbols then
            local filename = cfg.buildtarget.basename
            if filename == "vm-viewer" then
                premake.w('<ProgramDataBaseFileName>$(OutDir)vm-viewer_exe.pdb</ProgramDataBaseFileName>', filename)
            end
        end
    end)

    premake.override(premake.vstudio.vc2010, "additionalLinkOptions", function(base, cfg)
	    if #cfg.linkoptions > 0 then
		    local opts = table.concat(cfg.linkoptions, " ")
		    premake.vstudio.vc2010.element("AdditionalOptions", nil, "%s %%(AdditionalOptions)", opts)
	    end
    
        local filename = cfg.buildtarget.basename
        if filename == "vm-viewer" then 
            premake.w('<ProgramDatabaseFile>$(TargetDir)$(TargetName)_exe.pdb</ProgramDatabaseFile>', filename)
        end
    end)
`

**Comment by tapika** [comment]
P.S. This was raised by me as an issue here:

https://github.com/premake/premake-core/issues/319

**Comment by sztomi** [comment]
I would like to add more information to this issue, because I also face this and I strongly believe that the VS default is wrong in some use cases and the users need control over this setting.

First of all, my use case:
  * I'm deploying a static library with four configurations: (Debug, Release) x (32bit, 64bit)
  * I'm linking this library in target projects with debugging information turned on regardless of the configuration
  * I'm using a debug postfix `d` for the debug targets and my output directory sturcture looks like this:

```
lib/
 |--- x86/
 |     |--- mylib.lib
 |     |--- mylibd.lib
 |
 |--- x64/
       |--- mylib.lib
       |--- mylibd.lib
```
  
The VS default setting for the compiler-generated PDB is $(ToolSet).pdb (i.e. vc120.pdb for VS2013). This means that all configurations get the same pdb. It is also not generated in the target directory but rather in the intermediate dir. If I don't deploy this file with the libs, I will get linker warnings that the pdb is not found. If I can't change the name, I can't deploy the pdb unless I change to a deeper directory structure.

Another important piece of information: **There are actually two types of PDB files**. One is generated by the compiler (this is the one I discussed above) and the other is generated by the linker. The first one is controlled by the /Fd switch, the second one is by the /PDB switch (passed to the linker).
