### ISSUE TITLE
How to change then externalrule's value?

### ISSUE THREAD

**Issue by leeonix** [premake/premake-core#159]
In issue #126. you fix using externalrule's problem.
but that's an other question. how to change the property value?
I wrote this code:
```Lua
    rules { 'ragel' }
    externalrule 'ragel'
        location 'ragel'
        filename 'ragel'
        fileextension '.rl'
        propertydefinition {
            name  = "OutputFileName",
            kind  = "string",
        }

--    filter { 'configurations:Release' }
        ragelVars {
            OutputFileName = 'src\\%(Filename).c',
        }
```
error message is:
```
Error: [string "src/base/rule.lua"]:7: unable to set _rule_ragel_OutputFileName in rule scope, should be config
```
I need change output dir and the file ext and other option.
but I don't know how to change.
please explain this. thank you.

**Comment by starkos** [comment]
Property values can only be set in the context of a project or a solution. If you want it to apply to all of your projects, you could do something like this (untested):

```lua
-- define the rule first
externrule 'ragel'
   fileextension '.rl'
   -- and the rest of it…

-- then use it
solution "*"
   rules { 'ragel' }
   ragelVars {
      OutputFileName = 'src\\%(Filename).c'
   }
```

**Comment by leeonix** [comment]
Yes! It is work.

**Comment by leeonix** [comment]
But another question is:
although to use `externalrule` `.target` and `.xml` define the rule.
but property, the `.props` file maybe need to change.
these use my external rule
```Lua
externalrule 'ragel'
    location 'ragel'
    filename 'ragel'
    fileextension '.rl'
```

use  these 
```Lua
rules { 'ragel' }
propertydefinition {
    name  = "OutputFileName",
    kind  = "string",
}
```
maby generate a new `ragel.props` to use.
the property maybe define in `.vcxproj`, maybe define in `.props`
do you think that is a good choice?

**Comment by starkos** [comment]
The `externalrule()` call tells Premake to use the `.props` file that is already on the disk. If you want to write values to the rule files you need to generate them yourself, using `rule()` instead of `externalrule()`. In the case the code is doing the right thing.

You need to generate the entire rule (`.target`, `.xml`, and `.props`) or use the ones you already have. They all go together. So if you need changes in the `.props` file, and you want to use `externalrule()`, you will have to make the changes manually.
