### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by englercj** [premake/premake-core#1591]
Howdy!

Its been almost a year since the last release, and a lot of great improvements have come in since then. I consume premake via the pre-built binaries, so I'd love to see a new release so I can get access to all the new goodies.

Thanks!

**Comment by samsinsane** [comment]
If master builds will suffice, you can find builds of master [here](https://github.com/premake/premake-core/actions?query=branch%3Amaster+event%3Apush), there are artifacts attached to the workflows.

As for the next alpha release, this will continue to be a case of "when it happens" due to various time constraints.
