### ISSUE TITLE
how to set linker flag in premake

### ISSUE THREAD

**Issue by KittoChanKC** [premake/premake-core#1622]
**What's your question?**
Add any other background or context about your question here.

I am tried to use premake5 in my new project.

I want to set the linker flag (SUBSYSTEM:WINDOWS)in debug mode.
I tried to use `linkoption` but not work 

**Anything else we should know?**
something like this, I do in cmake.
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} /SUBSYSTEM:WINDOWS")

**Comment by starkos** [comment]
Showing us how you did it in CMake doesn't really help us help with Premake. Can you please show a _small_ example that demonstrates the issue (and next time fill in the issue template instead of just deleting it)? The correct way to script it is:

```lua
filter { 'configurations:Debug' }
    linkoptions ' /SUBSYSTEM:WINDOWS'
```

Did you check to see if the flag is being written into the `.vcxproj`? It's possible that your script is working, but the value is being overridden by the value of the `<ConfigurationType>` element.

**Comment by KittoChanKC** [comment]
I am sorry, I updated the the issue with template.

I checked project->property->linker->system->subsystem ,it not changed to WINDOWS. 
So I thought it`s not work before.

But checked in .vcxproj the value is overriding.
And run the project It`s working.

Thank for you help!
