### ISSUE TITLE
Premake5 alpha 16 - cppdialect c++20 still not working?

### ISSUE THREAD

**Issue by Pirulax** [premake/premake-core#1623]
**What's your question?**
I've seen #1516, and #1460. I took a look at alpha 16's release note, and it includes #1460, yet it doesn't seem to work. 
Error message: `Error: invalid value 'c++20' for cppdialect`.

**Anything else we should know?**
If needed I can provide my premake scripts.
CLI args: `premake5.exe vs2019`

~~I tried with `c++17` but then: `Error: [string "vstudio/vs2005.lua"]:9: attempt to index a nil value (field 'sln2005')`~~
Edit: Turns out this error was from a mistake by my side (something to do with calling `vpaths` before `files` IIRC)

*(You can now [support Premake on our OpenCollective](https://opencollective.com/premake). Your contributions help us spend more time responding to questions like these!)*

**Comment by Pirulax** [comment]
Okay, so it seems like I misunderstood the release notes.
alpha16 doesn't include the listed PRs?
I cloned the current soruce code, built it, and it works.

**Comment by samsinsane** [comment]
@starkos are you able to confirm the binary you uploaded? The version says alpha16, and the tagged commit contains all the listed PRs, but the binary (Windows at least) doesn't contain any of them. C++20 isn't an allowed value for `cppdialect` and the `COPYFILE` and `COPYDIR` tokens aren't in there either. Also, the release says "Changes since 5.0-alpha16" but it should say "Changes since 5.0-alpha15".

**Comment by starkos** [comment]
Maybe the embedded scripts didn't get updated somehow? I've rebuilt it and verified that "C++20" works for `cppdialect`. @Pirulax Could you [download from the release page](https://github.com/premake/premake-core/releases/tag/v5.0.0-alpha16) and verify that it now works for you?

**Comment by samsinsane** [comment]
I'm going to close this off assuming that it all works now.

**Comment by haolly** [comment]
@Pirulax  can you provide your solution? I'm encounter the same issue
