### ISSUE TITLE
Visual Studio C# Project - Symbols "Off" seting debugging information to "pdbonly"

### ISSUE THREAD

**Issue by Xeros08** [premake/premake-core#1670]
I have the following filters set inside a **premake5** project declaration for a C# SharedLib project:

```lua
filter "configurations:Debug"
        symbols "Off"
        defines { "DEBUG", "TRACE" }

filter "configurations:Release"
        defines { "TRACE" }
        optimize "On"
```

This is part of the resulting vs2019 project file:
```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\..\Assemblies\</OutputPath>
    <BaseIntermediateOutputPath>obj\Any CPU\Debug\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
```
As you can see `<DebugType>` has been set to `pdbonly` instead of `none`.
I have tried with the other `symbols` values, bot none disables it completelly.

Even if its not a bug and its intentional, sometimes completelly disabling debugging information is needed, and there should be an option to do so.

**Comment by nickclark2016** [comment]
@starkos @samsinsane I propose that we do the following:

- Off - Sets C# projects to `none`
- PdbOnly - Sets C# projects to `pdbonly`

Questions that this raises is what do we do for the case where `PdbOnly` is set in a C++ project.  If we want it to generate successfully, we could alias this to the existing `Full` option, as this is probably the closest debug info flag in VS2017/19.  We could also exit with an error instead of trying to resolve it in C++ projects.

I think because premake5 is still in alpha, this breaking change is okay.   If this is something that seems reasonable, I can go do this pretty easily.

**Comment by starkos** [comment]
I agree that "off" means off. I'm uncomfortable proliferating more VS-specific values into `symbols`, but I'm not coming up with a great alternative off the top of my head. We already have "Full" and "FastLink" but neither of those map cleanly. I guess my best take would be to add a new "PdbOnly" value and map it to "On" for other languages?

Does anyone know of another language that makes this distinction?

(In case I'm not the only one uncertain of the difference between the C# "full" and "pdbonly" debug types, [here's a quick explainer](https://stackoverflow.com/a/7713781/93921).)

**Comment by nickclark2016** [comment]
Course of action that will be taken here:

1. Add `PdbOnly`
2. Map `PdbOnly` to `pdbonly` for C# VS projects
3. Map `PdbOnly` to `On` for C++ projects

**Comment by nickclark2016** [comment]
Or another potential approach:

| Premake Symbol Value  | Visual Studio C# Project Value |
|-----------------------|--------------------------------|
| Off                   | none                           |
| On, FastLink, Default | pdbonly                        |
| Full                  | full                           |

I think this is the approach that we want.

**Comment by nickclark2016** [comment]
> 
> 
> | Premake Symbol Value  | Visual Studio C# Project Value |
> |-----------------------|--------------------------------|
> | Off                   | none                           |
> | On, FastLink, Default | pdbonly                        |
> | Full                  | full                           |
> 
> I think this is the approach that we want.

Just want to nudge on this.  I think the latter option is this best path forward on this.  If I don't hear anything in the next few days, I'll implement this option over the coming weekend.

**Comment by starkos** [comment]
The only thing that jumps out at me is "Default", which should match whatever VS would do if you create a new project manually through the IDE. For C# projects, I _think_ that means "full" for debug builds and "pdbonly" for release, but that's off the top of my head. Otherwise, this seems a reasonable mapping of the C++ values to me.

**Comment by nickclark2016** [comment]
Sounds good. I'll do some investigation, then write that in the PR.
