### ISSUE TITLE
About optimize() function question

### ISSUE THREAD

**Issue by lailongwei** [premake/premake-core#1892]
I used `optimize()` function in my premake file, see below code:
```lua
filter { "configurations:debug*", "language:c++" }
    optimize "Speed"
filter {}
```

when i execute `make` command, I found premake generated optimize option is `-O3`, not `-Os` or `-O2`, I want to know why?
*PS: use `optimize "On"` has same effect*

-- premake tool version: `premake5 (Premake Build Script Generator) 5.0.0-alpha15`
-- optimize options doc: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options

**Comment by samsinsane** [comment]
> I want to know why?

- `-Os` is for _size_ not _speed_, the docs you linked state this.
- `-O2` does not include optimizations that involve "size-speed tradeoff", the docs you linked state this.
- `-O3` enables all of the `-O2` optimizations, and more.

> _PS: use `optimize "On"` has same effect_

You might be overriding the setting because `On` is mapped to `-O2`, you can see that [here for alpha15](https://github.com/premake/premake-core/blob/v5.0.0-alpha15/src/tools/gcc.lua#L72) and [here for current latest](https://github.com/premake/premake-core/blob/dc02a676e70cc1f7090e8608344c34881dfaf05e/src/tools/gcc.lua#L75).

**Comment by lailongwei** [comment]
@samsinsane Thank you very much, it's my problem!
