### ISSUE TITLE
precompiled header support bug

### ISSUE THREAD

**Issue by kinsung** [premake/premake-core#222]
When I use the pchheader function to set the main header file for precompiled header support.
pchheader "stdafx.h"
pchsource "stdafx.cpp"

but the sln and vcproj file were generated and go building,  and get much errors:

1>myproject\some.cpp(4) : fatal error C1083: Cannot open precompiled header file:“d:\myproject.pch”: No such file or directory

I open the .vcproj file, fix the code as following, it is fine.

<File RelativePath="myproject\stdafx.cpp"></File>

change to :

`<File
            RelativePath="myproject\stdafx.cpp"
            >
            <FileConfiguration
                Name="debug_shared|Win32"
                >
                <Tool
                    Name="VCCLCompilerTool"
                    UsePrecompiledHeader="1"
                />
            </FileConfiguration>
            <FileConfiguration
                Name="release_shared|Win32"
                >
                <Tool
                    Name="VCCLCompilerTool"
                    UsePrecompiledHeader="1"
                />
            </FileConfiguration>
            <FileConfiguration
                Name="reldbg|Win32"
                >
                <Tool
                    Name="VCCLCompilerTool"
                    UsePrecompiledHeader="1"
                />
            </FileConfiguration>
        </File>
`

**Comment by NicolBolas** [comment]
I'm getting this error too. It seems to be due to the fact that the PCH source file is not in the same directory as the project. For some reason, the VS* build system assumes that the PCH will be in the project's root directory.

**Comment by starkos** [comment]
Have you looked at the [Precompiled Headers](https://github.com/premake/premake-core/wiki/Precompiled-Headers) article on the wiki?

**Comment by NicolBolas** [comment]
Yes. I followed each directive:

> If you want your code to build with precompiled headers in Visual Studio, your #include statement must be exactly the same in all source code files.

Done. For my project, all source files begin with `#include "pch.h"`.

> When specifying the PCH header in your Premake script, the value provided should match the value in your source code's #include statements exactly.

Also done. The Premake5 directive is `pchheader "pch.h"`. Note that "pch.h" is *not* in the same directory as the premake script. It lives in `source/pch.h` relative to the script.

> The value provided to pchheader is treated as a string, not a path and is not made relative to the generated project file. Rather is it passed through as-is.

That's why I write `pchheader "pch.h"` instead of `pchheader "source/pch.h"`.

> If you have multiple folder levels in your source code tree, you must add the folder containing the header to be precompiled to your include file search paths.

Also done. The `source` directory is in the `includedirs` path.

What I'm getting when I build the projects for VS2015 is that VS2015 thinks that there are two `pch.cpp` files. One is `source/pch.cpp` (which is the actual precompiled header's source file). The other is `pch.cpp`, aimed at the project directory; no such file exists, nor did my file inclusions specify one.

So when I go to build the project, VS2015 says that it can't compile `./pch.cpp`.

If you want, I can post the whole project script.

It should also be noted that my files and directory organization was working under Premake4.

**Comment by starkos** [comment]
Shouldn't that be `pchsource "source/stdafx.cpp"`?

**Comment by NicolBolas** [comment]
Yes, I copied that into the message incorrectly. In the actual Premake script file, it's `pchsource "source/pch.cpp"`.

**Comment by NicolBolas** [comment]
> Shouldn't that be `pchsource "source/stdafx.cpp"`?

Are you referring to the name of my source file? If so, nothing was ever said about it *having* to be called "stdafx.cpp", and I rather doubt that Visual Studio imposes that requirement. Nor did Premake4.

If you're talking about the `pchsource` command in general, that command is `pchsource "source/pch.cpp"`. Which it was under Premake4.

**Comment by sleepyspider1** [comment]
The problem I had with this was the pch was not being generated by default. By default the setting is "Use" not "Create", when building, which results in the error that it can't find the actual PCH. As a workaround, after generating the project, I have to first generate the pch by right clicking "stdafx.cpp" and setting the "Use" flag to "Create" to generate the pch. Note, that this is a setting for the stdafx.cpp file, and not the project or any other file. This occurs for me under premake 5 Alpha 13.

This doesn't have anything to do with finding the stdafx.h file or pathing issues, as long as you have stdafx.h at the top of every file and it's in the include paths list.

**Comment by harryisgamer** [comment]
I am having the same issue as @sleepyspider1, so I think precompiled headers might just be broken right now for the VS actions.

**Comment by KrisSiegel** [comment]
Was this issue ever resolved? I just ran into this today and I don't see a way to tell premake5 to generate the project file to use `Create` instead of `Use` for precompiled header files. Just like @sleepyspider1 I can just change my project from `Use` to `Create` for precompiled headers and it works just fine.

**Comment by KrisSiegel** [comment]
I was able to resolve the issue by playing around with the path. Though, as it originally was, all I had to do was swap the flag from `/Yu` to `/Yc` and it worked just fine.

Seems kinda error prone, especially with so many topics revolving around this issue. If a simple option was added to override the flag for VS I think that would be fine. That or maybe improving the handling of this a little more so it can better detect the pathing that VS seems to pick up just fine.
