### ISSUE TITLE
Sources in releases

### ISSUE THREAD

**Issue by alex-rass-88** [premake/premake-core#2325]
Release tag on eb5238f commit. At github i see Thread sanitizer added. But if i download file (https://github.com/premake/premake-core/releases/download/v5.0.0-beta3/premake-5.0.0-beta3-src.zip) Thread sanitizer not supported. This is older version in archive?

**Comment by nickclark2016** [comment]
It looks like thread sanitizer missed the beta3 cut by a few hours. I cut the sources for the beta3 release while #2315 was still an open PR.

**Comment by Jarod42** [comment]
BTW, doc doesn't mention availability version of the new entries :-/
`Thread`, `UndefinedBehavior` will only be available in 5.0.0.beta4 (or nightly, or self built).

**Comment by alex-rass-88** [comment]
If you download the archive generated by github, then thread sanitizer is present there. It doesn't feel right.

**Comment by nickclark2016** [comment]
It is a bit weird, yes. We really need to get a better mechanism to build releases on GH, since this is just an artifact of manual release artifact generation.  What happened here is:

1. Release 5.0 Beta 3 Candidate sources were cut from master (artifacts generated here)
2. Things were merged to master (including TSan)
3. Release 5.0 Beta 3 Candidate was merged back to master
4. Release 5.0 Beta 3 Released with artifacts from step 1

**Comment by alex-rass-88** [comment]
It's a little confusing. But not critically.

**Comment by nickclark2016** [comment]
I completely agree that it's weird. There need to be better safeguards on our end to prevent this type of situation in the future.
