### ISSUE TITLE
Works with code:blocks, not gmake

### ISSUE THREAD

**Issue by starside** [premake/premake-core#339]
I am having issues with the gmake generated Makefile.  premake4 generates the correct codeblocks build file, but fails with the gmake.  I think it has something to do with spaces in the names of files.  Unfortunatly, my gmake comprehension skills are too lacking to debug.

Here is the makefile output

```
==== Building framework (debug) ====
==== Building Tut 02 Fragment Position (debug) ====
==== Building Tut 02 Vertex Colors (debug) ====
Creating obj/Debug/Tut 02 Vertex Colors
VertexColors.cpp
g++: error: 02: No such file or directory
g++: error: Vertex: No such file or directory
g++: error: Colors/VertexColors.d: No such file or directory
make[1]: *** [obj/Debug/Tut 02 Vertex Colors/VertexColors.o] Error 1
make: *** [Tut 02 Vertex Colors] Error 2
```

I have
```
premake4 (Premake Build Script Generator) 4.4-beta5
```

I think the 02 is from "Tut 02".  I cannot seem to attach files, so I will email them if interested.  Alternately, you can download them here https://github.com/Tsarpf/ducking-octo-dangerzone/tree/master/Tutorial%200.3.8

**Comment by tkarv** [comment]
I know this is an old post, but I had this same problem trying to compile the same project (OpenGL tutorial from http://alfonse.bitbucket.org/oldtut) and from quick googling didn't find a solution posted anywhere online. 

It seems the problem is caused by premake4 not handling the whitespace characters within the project name well when using gmake. In this case, to get the project to correctly compile with make, eliminating the whitespaces from the project names from **tutorials.lua** inside the tutorial folder, e.g. changing:

```
SetupProject("Tut 02 Fragment Position", "FragPosition.cpp",
"data/FragPosition.frag", "data/FragPosition.vert")

SetupProject("Tut 02 Vertex Colors", "VertexColors.cpp",
"data/VertexColors.frag", "data/VertexColors.vert")
```



to

```
SetupProject("Tut02FragmentPosition", "FragPosition.cpp",
	"data/FragPosition.frag", "data/FragPosition.vert")
	
SetupProject("Tut02VertexColors", "VertexColors.cpp",
	"data/VertexColors.frag", "data/VertexColors.vert")
```

allows the project to compile. Escaping the whitespace within the quotes didn't seem to help. Beyond that, how to fix the issue within premake4, I don't have an idea.

**Comment by starkos** [comment]
I don't think anyone is currently working on Premake4. You can try it with Premake5 (http://premake.github.io), or submit a PR against the Premake4 repo to fix it?
