### ISSUE TITLE
contrib libraries' Visual Studio projects require toolset version 12.0 which break compilation with older Visual Studio versions

### ISSUE THREAD

**Issue by manxorist** [premake/premake-core#383]
Building 5.0.0-alpha7 with Visual Studio 2010 results in
```
1>------ Build started: Project: zip-lib, Configuration: Release Win32 ------
1>Build started 24.12.2015 15:05:07.
1>Project file contains ToolsVersion="12.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(518,5): error MSB8008: Specified platform toolset (v120) is not installed or invalid. Please make sure that a supported PlatformToolset value is selected.
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.09
```
(and similarly for curl and zlib)
I think premake should provide individual project files for each Visual Studio version for every contrib library (the same way as it does for premake itself). That is what I am doing for my own projects.

**Comment by samsinsane** [comment]
@starkos was the idea for VS to prompt the user to upgrade the contrib library project files if they ran a newer version? I can see some value in providing the project files for each version of Visual Studio, I've seen the upgrade utility fail a number of times with open source projects, so it might be worth ensuring we don't have this problem?

Also, we should add in files for VS2015 if possible.

**Comment by starkos** [comment]
I think the actual problem here is that the contrib libraries are putting both their project and intermediate files in their own directories, which causes them to get overwritten each time we generate new project scripts.

I would like to see all of the project files put in the same folder (or just merge everything into one project; there is really no need for separate projects here), and the intermediate files placed in `obj/`, and the libraries placed in a top-level `lib/` (or again, just have one project that builds everything, then we don't need the libraries and everything gets a little simpler).

If you look at line 145 in `package.lua` you can see where I'm generating projects for a bunch of different versions. Each subsequent call is overwriting the previous project files in `contrib/`.

**Comment by tvandijck** [comment]
https://github.com/premake/premake-core/pull/394

**Comment by tvandijck** [comment]
I think all this has been resolved in both the bootstrap.mak file (using the MSDEV macro), as well as the removal of the location overrides in the contrib libraries... it should be easy now to generate projects for any version of visual studio with either workflow.
