### ISSUE TITLE
Performance discussion/issues

### ISSUE THREAD

**Issue by samsinsane** [premake/premake-core#442]
A [discussion](https://groups.google.com/d/topic/premake-development/UBy78gGwkks/discussion) was started on the forums regarding performance in alpha7, but has since timed out for replies. I figured we should probably have an issue open here to allow an ongoing discussion about performance and internal changes that need to occur to do this. It seems that our first problem is the `configset.compile` function, so are there any ideas for how to reduce the cost of this function?

Additionally, how should we go forward in terms of managing the performance of Premake? Should we create tools, or tests, to profile Premake better? @tvandijck [mentioned](https://github.com/premake/premake-core/issues/221#issuecomment-134270114) some numbers for one of the projects at Blizzard, should we replicate this situation and use it as our stress test? It's a real world case where Premake is being used, and it looks like it highlights some of the performance issues that Premake has on larger projects.

Would there be a benefit to having a mode where Premake can store data from the previous run, such as a hash of the previous script, the previous action and the names of all the files that were found (or used?) in the last run? And using this to do an early exit if nothing has changed.

**Comment by tvandijck** [comment]
I wrote a profiler https://github.com/Blizzard/premake-core/commit/b77564db8ab076040aefacf506e0ddef528ec8cf

and a simple C# tool to parse the output from that... it has a lot lower overhead then the lua pepperfish one, and I find the output somewhat more usefull too... but it's build on lua 5.3, and I'm not sure if the facilities are available in 5.1... we would have to test that...

That said, I think it is worthwhile to have the profiler embedded into the project... either disabled with a define, or just how we did it with a "--profile" command line option, but always available.
Certainly with compiling using --bytecode, the profiler gives pretty accurate information as to where the bottlenecks are, and I was going to try and add C function callstack information to the system as well, by parsing the pdb information in the C# tool, I just never got to that.

Then as for bottlenecks... on our project we heavily use the vpaths, so I cached the results of that, which seemed to help quite a bit: https://github.com/premake/premake-core/pull/275
That pull request however has some other changes embedded into it, so we'd have to separate that out.

I haven't looked into configset.compile, But the one thing I do know is that 90% of the performance and memory sits in constructing tables and strings, which is obviously obvious, since that is pretty much all lua can do... But I think the biggest boost we can get, is by not copying so much data all the time. Basically the way premake works, is by having the user construct an "AST", which premake in the bake process then converts into a different "AST", which the action then converts into a file. It feels like a lot of the baking process can be done on demand during the conversion into the file, which may result in some parts never having to bake, since it's unneeded for that action.

For example, we made changes to the configset.compile at some point to fully bake the filecfg or something like that... but that was specifically to assist our xcode action, no other action benefits from that... and there is a few other places where that is the case.

Other then that, a lot of the baking could potentially be done into C structs, instead of lua tables. Kind of like the approach I took with the buffered_io. Lua tables aren't really that slow, if used as a table or array... but when it is really just a struct of data that always has the same members, they are horrible, since every member lookup is a hash-table search... 

Then lastly, I can imagine that in other then the users API, there is no need for lua for any of the rest.. actions, baking, it can all be C... it's just a lot of work :)

**Comment by starkos** [comment]
There is a profiler and a tunable stress test in the `tests/` folder; improvements to either or both of them are of course welcome. It would be great to add some `vpaths` to it, for instance.

Improving performance is always a good thing, and Premake could certainly stand to be faster. But keep in mind that this is a tool that is intended to be run once up front, and then off you go with development. To my mind, usability and customizability are more important than performance—which is why I moved most of the code from C to Lua in the first place.

And in that regard, the current oven/baking approach has a number of drawback in addition to the performance that I'd like to address (I don't want to derail this thread, but in particular it can't tell you "what settings on this file/config/project are different from its containing scope?", which I really need to improve the Xcode and makefile exporters. And don't even get me started about file configs…) Figuring that out is currently top of my to-do list and I'm hoping to have something to show soon; I mention it because `configset.compile()` will possibly (but not definitely) be going away.

> Other then that, a lot of the baking could potentially be done into C structs, instead of lua tables

In my attempts, the marshaling costs overwhelm the gains. You end up having to move everything to C to make up for it, and then you lose the ability to extend/override unless you make all your calls through Lua, in which case the marshaling costs overwhelm the gains :p

> Then lastly, I can imagine that in other then the users API, there is no need for lua for any of the rest.. actions, baking, it can all be C...

Yikes please no, I override that stuff all the time, especially the actions. I will definitely push back if things start going in that direction.

**Comment by tvandijck** [comment]
> Yikes please no
Well, I was speaking hypothetically really... I have no intent to undertake something like that.

**Comment by samsinsane** [comment]
Wow, looks like I didn't really need to open the issue, you guys already had things ready to go to address some of the issues. I think we should definitely get that profiler in to core, @tvandijck. While pepperfish does a good enough job to find the bottlenecks, it would be nice to have some stats on the C functions that are called. (It didn't look like pepperfish was aware of any of the C functions, I could be wrong though?)

**Comment by starkos** [comment]
Also take a look at [Shiny](https://sourceforge.net/projects/shinyprofiler/), and [Glider](http://www.mydevelopersgames.com/Glider/index.html) has been on my to-look-at list too.

I'm not opposed to having a profiler embedded into Premake, it would be useful. But ideally Premake should be fast enough that end-users don't particularly care, and we will just profile our development builds as needed. But, either way.

**Comment by tvandijck** [comment]
Shiny seems really old, and it basically uses the same hooking API I use for the little thing I wrote. 

Glider looks very interesting though, it does require a little bit of lua code in our startup code, but that seems relatively easy.. we can probably even just do that with the curl library we already have.

> But ideally Premake should be fast enough that end-users don't particularly care, and we will just profile our development builds as needed.

Agreed, but I find it rather difficult to use things like Codera, and other IDE's and even to get Glider to work we have to add code... so in the end we have to do something extra to allow us to profile/debug the lua code.

**Comment by starkos** [comment]
I wouldn't mind building in integrations for third-party IDEs and debuggers, maybe something like `--debugger=glider` on the command line?

**Comment by samsinsane** [comment]
> But ideally Premake should be fast enough that end-users don't particularly care, and we will just profile our development builds as needed.

I agree, I've found Premake to be fast enough in pretty much all cases. But that being said, Premake takes around 400ms to generate my projects and I think we could reduce that significantly. :)

**Comment by tvandijck** [comment]
> Premake takes around 400ms to generate my projects

I envy all your peewee tiny projects ;) haha
23000 ms here, although admittedly about 8000ms of that is http queries to our package server, which we should also fix, but that is our problem...

**Comment by samsinsane** [comment]
Going to close this issue, it's overly generic and will never truly be resolved. There's potential solutions to some of the existing bottlenecks, and if there's a specific bottleneck that needs to be looked into, people can report these individually.
