### ISSUE TITLE
Lua Upgrade

### ISSUE THREAD

**Issue by neico** [premake/premake-core#446]
Yes I know this has been at least mentioned a few times, but then there's this repo being pretty fresh and changing a lot of things that result in behaviour change (or even compatibility breaks) anyway, so why not leap a step forward onto that?

And now that lua is packed into contrib instead of inside the core itself you can switch between things a lot easier.
I'd suggest removing lua entirely from the repo and use https://github.com/lua/lua as a submodule (you can use a branch option to select the different versions). This allows custom builds to just switch out the version (given that the premake core is checking against the version to make sure it's code doesn't break in-between)
You could also make a new branch on the repo to let people test premake with 5.3 in advance to merging it into master
### To cover some questions:

LuaJIT might, or might not adapt to changes in 5.3 at some point ([they also have a 5.2 switch to support pretty much everything from 5.2 except for api changes like _ENV, so there's hope at least](http://luajit.org/extensions.html#lua52))
[Lua 5.2 Incompatibilities with 5.1](http://www.lua.org/manual/5.2/manual.html#8)
[Lua 5.3 Incompatibilities with 5.2](http://www.lua.org/manual/5.3/manual.html#8)
### To quote the website:

Lua 5.2: "Its main new features are yieldable pcall and metamethods, new lexical scheme for globals, ephemeron tables, new library for bitwise operations, light C functions, emergency garbage collector, goto statement, and finalizers for tables."

Lua 5.3: "Its main new features are integers, bitwise operators, a basic utf-8 library, and support for both 64-bit and 32-bit platforms."

---

So all in all, you get from 5.2 more technical toys to play with, but the language itself also has good stuff.
goto for example allows to emulate "continue", without a 3rd party patch.
It also makes the internal environment easier to handle, namely _ENV (this is probably where most people argue about, but it has become easier, if you use it for a while you'll notice it).
You can finally use bitwise operations, together with the added hex code specifiers you can now build nice and fast flag systems. (There's more but I haven't used all of those yet so I can't give an opinion about those)

Lua 5.3 adds further needed things, which the website summary explains pretty well already imo.
Integers can be a lot faster to compute in some cases then floats are (which is what lua numbers so far were)

---

It's all a matter of how you use lua and how well you do your stuff.

If there really are projects that depend upon premake remaining on 5.1 then make it switchable like I mentioned in the beginning or at least start naming them here to review upon them if there aren't alternatives or how to fix them.

From my viewpoint there aren't many valid reasons not to upgrade...

**Comment by starkos** [comment]
I'm fine with upgrading the Lua runtime, but maintaining source compatibility with 5.1 (via shims or whatever) would be very helpful, as I have a number of deployments where Premake has been integrated with other tools that are still on the 5.1 runtime. 

I don't think we want to switch to LuaJIT though. I'd prefer to stay on the official runtime.

**Comment by tvandijck** [comment]
> but maintaining source compatibility with 5.1 (via shims or whatever)

That's where the issue comes in with upgrading, some things can certainly be done through shims, but the fact remains that the bootstrap.mak is already not backwards compatible, considering there is a number of additional or less files in 5.3.2 compared to 5.1..

But the biggest issue is with the "lua_auxlib.c" overrides, which have to be done on a different method altogether, with a different signature.. It maybe can be done with an "#ifdef LUA_VERSION==..." or something, if LUA exposes something like that.

There is a bunch of stuff on the lua side that are pretty different.. I have fixes in _premake_main.lua, make_workspace.lua, detoken.lua, premake.lua and table.lua, none of which are backwards compatible with 5.1.

"setfenv(func, e)", or "loadstring" in detoken for example doesn't even exist in 5.3.2, instead you have to load directly into the enviroment using "load("return " .. token, nil, 't', e)", etc.

"unpack" used to be a global method, starting with 5.2 that became a method of table. I guess a shim for that is possible, but the whole idea of that 'switch' was that starting with 5.2 the global namespace is somewhat off limits.. polluting it with 'shims' to gain 5.1 backwards compatibility goes entirely against that idea, besides this is the only one I can see where that is even really possible anyway.

"local index = minindex + bit32.arshift(maxindex - minindex, 1)"
in 5.3.2 is written as:
"local index = minindex + ((maxindex - minindex) >> 1)"

then on the C side, I guess most can be done using #ifdefs, but it ain't going to be pretty.

Honestly, I rather put these changes in a separate branch, that we rebase on master once in a while, rather then making it part of the official release.. besides that however, there is no benefit whatsoever in switching... it doesn't give performance, nor extra features. The new features in 5.2 and 5.3 are awesome, but if we need to keep backwards compatibility with 5.1, we can never use them.

**Comment by tvandijck** [comment]
FWIW though... this changes upgrades premake to 5.3.2.
https://github.com/Blizzard/premake-core/commit/4e9770718f70d247edd65370d6bd38691effd293

but without considering backwards compatibility or the ability to switch between versions, we just keep up to date with latest, and that's it.

**Comment by neico** [comment]
This commit alone is so big that you're going to have a hard time comparing, this is very bad practice.
as I said, removing lua from the repo altogether to gain the ability to dynamically switch it with different versions is the only way to go if you want to avoid such commits and keep things flexible.

Also, [lua/lua/blob/master/src/lua.h#L21](https://github.com/lua/lua/blob/master/src/lua.h#L21) / [lua/lua/blob/master/src/lbaselib.c#L496](https://github.com/lua/lua/blob/master/src/lbaselib.c#L496), makes it easy enough to do #ifdefs / version specific code no?

Hiding away the changes to the end-user is therefore relatively easy, the question is do you want premake to base it's environment on 5.1 and add forward-compatible adjustments or 5.3 and add backward-compatible adjustments? (This one's probably the most important part to decide before doing anything else, both sides are theoretically possible)

And yes I also said that I'd use a separate branch next to master (let's call it lua-next or so) to work on this and iron it out until it works in all situations, at this point it'll be ready to be merged into master. (I'd expect this to last for at least a year in that branch before merging)

Also pretty sure that bootstrap could be made a lot easier, like auto detection of the files (catch all except for lua.c and luac.c) but those are specifics that would need to be handled when it's actually happening...

**Comment by tvandijck** [comment]
> This commit alone is so big that you're going to have a hard time comparing, this is very bad practice.

it's just replacing lua, if that is bad practice to do in a single commit, I don't even know how else to make that commit. But whatever... removing it from the repo doesn't feel like an option, it would make building premake even harder, people are already not getting the bootstrap process, so lets not make it even more complicated.

using #ifdefs for the C/C++ parts, I'm OK with. But again, some of the lua changes are just not compatible at all. Hiding those or making them switchable, I just don't see how, but I'm no lua expert, so feel free to proof me wrong.. I gladly review and learn from it.

That all aside however, what do we gain from switching? The new features in 5.3 we can't use if we need the ability to switch back to 5.1? and in terms of performance 5.3 is actually slightly slower for premake. If we gain nothing, but now have to maintain two branches, and extra code to keep things compatible, it's just more work for the few people that are maintaining premake at the moment. It's mostly just Jason, and once in a while when I have time I help out, and that's the same for a few others, but it basically comes down to just Jason. 

That said, clearly my 5.3.2 upgrade commit is shit. But you are free to make pull requests, we can always use the help, it be easy to merge it into a side branch for testing. I never bothered to make a pull request out of it, since it's just not worth the effort if 5.1 compatibility is a requirement. For us here we use 5.3.2, but I've considered dropping the change, since it doesn't give us anything.

**Comment by tritao** [comment]
There is at least one feature from that 5.2 that at would be useful for us, `io.popen()` returns the process exit code from `close()`.

**Comment by starkos** [comment]
Can we backport that feature into our (already modified anyway) Lua 5.1 runtime?

**Comment by tritao** [comment]
Probably, I didn't even think about that. Will look into it if I manage to find some time.

**Comment by neico** [comment]
The Modules (D, CodeLite, etc.) alone are submodules already so it shouldn't be that much of a problem, even if you have only slight knowledge of git you should already know how to handle that...

5.3's improvement only apply when you compare things like tabe[1] versus table[1.0] where the float variant is slower.
Also, most features don't impact the premake environment directly (1 = 1.0 since lua existed, now with 5.3 both only got different types but are still handled the same essentially)
Here's a benchmark from the mailing list (feel free to look for more, I don't feel like searching for hours): http://lua-users.org/lists/lua-l/2013-07/msg00423.html
So it might be some other areas in your implementation that would need to be improved instead...

I'm not sure what each individual would profit from the upgrade.
But for me personally the goto feature is a pretty important improvement. As well as all the bitwise and hex stuff.
The garbage collector improvements might not apply as much as premake just doesn't run long enough to build vast amounts up.

I'd suggest to just try it out and gather feedback from the users by also providing nightly builds and see which roadblocks come along.

But that aside, I'd probably even voluntary to actively help get this branch done, even if only to put some load off starkos.

**Comment by samsinsane** [comment]
This sounds like an interesting idea, but I tend to agree with what @tvandijck is saying. It seems like this is going to be quite a bit of work, for very little pay off. If we need to maintain compatibility with 5.1, we couldn't use features from 5.2+.

Additionally, I would be worried about our module support here. There's incompatibilities between versions of Lua, so how would this work in the module area? If a user utilizes multiple modules, they would have to learn how to extend Premake in order to have all their modules work on the same version of Lua. Alternatively, module developers need to get every flavour of Premake and ensure their module is compatible, doesn't sound like that would increase contributions to Premake.

**Comment by neico** [comment]
Since theory doesn't seem to help here I started putting some of my ideas into action.

So far plain 5.3 doesn't seem work with premake out of the box, turning 5.1 compat (which also includes compat with 5.2) on however trims it down significantly to pretty much one remaining issue (if you ignore the trivial task of lua_dump having extra strip argument starting with 5.3, alas os.compile):

luaL_loadfile, since 5.1 this function was turned into a define (as it's now a alias of luaL_loadfilex) and the hack in lua_auxlib.c broke pretty much.

I'm still thinking in how to resolve this in the best way, currently I don't want to expand on this hack even more but rather try to get rid of it and do it more properly...

But aside from that I don't see much reason why compatibility would be a problem at all (one could start phasing out the combat features one by one after that, if premake is to move past 5.1 at some point)

In the long run lua is only going to keep moving forward and premake will be yet another app / lib that will be left behind if it isn't brought to date (and probably lose potential new users as your chance to find documentation, howto's, etc. on the newest lua version is usually bigger then in older versions, which people learn programming in lua from)

I can see the concern for modules, but since premake doesn't seem to use module() / setfenv / _ENV from lua at all this at least shouldn't hinder it, and as I said above, the compat features should ensure that code from 5.1 trough 5.3 will work in premake. (to which extend we'll see once I get past that hack)

I'll see if I can find something to make sure that premake can run with either lua version without forwarding the lua version decision to the end-user.

If you're interested I'll provide some diff's once I get it in a running state. (might be putting it into a fork repo at that point anyway...)

PS: I can see a few area's where premake could be improved upon, if this turns out to be junk on my part I'll make sure to at least salvage improvements from it.

**Comment by starkos** [comment]
Thanks @neico! 

Keep in mind that I said losing compatibility with 5.1 wasn't ideal, but that doesn't mean we can't decide to do it. 

I might have to push back on one deployment that is using 5.1 in their tools if we do, and I'd like to avoid that if possible, but if it should be done, then let's do it.

**Comment by tvandijck** [comment]
luaL_loadfile: I'm still thinking in how to resolve this in the best way:
https://github.com/Blizzard/premake-core/blob/master/src/host/lua_auxlib.c#L17

although, obviously, if you wish to get rid of it, and solve this differently, I'm all with you on this one.

> premake doesn't seem to use module() / setfenv / _ENV 

That's not true... premake.detoken.expandvalue uses setfenv...
https://github.com/premake/premake-core/blob/master/src/base/detoken.lua#L56
I fixed it like this:
https://github.com/Blizzard/premake-core/blob/master/src/base/detoken.lua#L50
the new 5.2 load takes the environment as an argument, setfenv is then not needed.

**Comment by tvandijck** [comment]
Also, I didn't setup the compat stuff, so I had to make more fixes obviously.. but since my commit is stupid in your opinion,  please don't look at it, and just redo all the work.. That said, all changes to get premake to work on 5.3.2 are in that commit... simply clone the repo, and look at the diff with gitk or something.

Admittedly, we don't use the standard xcode,codelite and d modules, so I made no effort to fix those.

**Comment by d-led** [comment]
For the sake of completeness, [luaconf.h](http://www.lua.org/source/5.3/luaconf.h.html) has macros in the form `LUA_COMPAT_*` that allow compiling older code with i.e. newer Lua versions.

**Comment by neico** [comment]
That's what I plan on using for now to keep things working, over the time things can be phased out by fixing code (or even add a deprecate message) to move things forward (LUA_COMPAT_5_1 has no use in 5.1, in 5.2 it adds 5.1 compatibility and in 5.3 it adds 5.1 + 5.2 compatibility)

For now I'm still fighting with bootstrap.mak to make it smarter, it can already detect if VS2010, 2012 or 2015 is installed and call things accordingly (I plan on PR'ing this out later on), the real issue is getting it to automatically detect the *.c files (as the amount and names differs with each lua version). On linux systems this shouldn't be a problem because of the backtricks, but windows as usual is a bit more complicated...

Maybe I'll just resort to a little hack to simulate different filenames across different versions...

**Comment by neico** [comment]
Guess it's time to close this one as @tvandijck hit the switch on this by now (and I lost most of my work on this by now anyway).
