### ISSUE TITLE
premake5 embed doesn't output luac warnings

### ISSUE THREAD

**Issue by nmoehrle** [premake/premake-core#505]
Erroneous lua files will not be embedded, without a warning.
The error only noticeable after compilation:

```
> premake5 embed
Running action 'embed'...
Compiling... 
Embedding...
Writing...
Generated ../src/scripts.c...

> premake make
==== Building lua-lib (release) ====
==== Building zip-lib (release) ====
==== Building zlib-lib (release) ====
==== Building curl-lib (release) ====
==== Building Premake5 (release) ====
scripts.c
Linking Premake5

> premake5
Error: cannot open actions/make/make_cpp.lua: No such file or directory
```

It would be nice to catch such errors earlier.

**Comment by tvandijck** [comment]
if you run "premake5 embed --bytecode" it'll actually give you errors during the embed stage, since it is trying to compile the lua files into bytecode.

normally however, the embedding doesn't try to load or otherwise do anything with the lua scripts, and just embeds them as strings straight into the binary... which is why an erroneous script will only fail on execution...

I guess however the error it give (no such file or dir) is somewhat unhelpful, and maybe even confusing, since the file really is there, it's just broken, so maybe we can at least fix that.

**Comment by nmoehrle** [comment]
Thanks :-)

I guess the ```Compiling...``` was throwing me of ;-)

**Comment by tvandijck** [comment]
Yeah, I'll have a look and see if we can at least fix the error message at runtime to something more useful... other then that I don't think we can do much else with the default embed process.

**Comment by starkos** [comment]
It would be nice to fix this, but I have to say that in all the years I've been working on Premake I've never encountered this. You are trying things out in debug mode first, right?

**Comment by nmoehrle** [comment]
I just quickly added a table entry, forgot a comma, ran `premake5 embed && make` and ended up cloning another repo because I couldn't replace the embedded code.

I guess it was naive, but my assumption was that since it said `Compiling...` that I could only break something within the nvcc toolset... Not going to happen again :-)

Luac has a option to just check the syntax is something similar available within lua itself?

**Comment by tvandijck** [comment]
Closing issue: "premake5 embed --bytecode" will run the embedded code through the compiler, and hence do syntax checking at embed time... other then running the embed this way, there isn't any kind of syntax checking in lua available really..
