### ISSUE TITLE
Premake bootstrap does not work w/ just 'Visual C++ Build Tools'

### ISSUE THREAD

**Issue by nta** [premake/premake-core#578]
```
        devenv .\build\bootstrap\Premake5.sln /Upgrade
'devenv' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'devenv' : return code '0x1'
Stop.
```

The [standalone build tools](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/) do not contain the IDE, including the `devenv.com` command-line binary for the IDE, and the shipped bootstrap makefile expects this to exist for /Update and /Build.

**Comment by tvandijck** [comment]
The question is... how do you build a .sln without devenv? should we use msbuild instead? the bootstrap for windows indeed does assume you have visual studio installed, since that is what the bootstrap targets...

since this fails in the step where it tries to build the .sln... it means it already generated one through the bootstrap binary... so if you know what command line to use to build that particular SLN, you should be able to get a full premake binary, and also tell us what command line you used, so we could use that instead of the devenv command line.

**Comment by ntauthority** [comment]
>The question is... how do you build a .sln without devenv? should we use msbuild instead? the bootstrap for windows indeed does assume you have visual studio installed, since that is what the bootstrap targets...

Yes, msbuild will convert a .sln to an internal project representation upon loading for compatibility behavior. Of course, /Upgrade doesn't exist here and it will use whatever toolset is set in the solution, so it should presumably be an override like the MSDEV variable.

**Comment by tvandijck** [comment]
I think you could easily try this out in the bootstrap.mak, change the windows target to use msbuild, and don't specify /upgrade.... I'd potentially just make a different target for it... so you could do:

```nmake -f Bootstrap.mak MSDEV=vs2015 windows-standalone```

or something.

**Comment by samsinsane** [comment]
I don't see any reason why the `devenv /Upgrade` command should be called if you specify `MSDEV`. Furthermore, I don't see any reason why we'd continue to use `devenv /Upgrade` when the developer can just specify their version of VS via `MSDEV`.
