### ISSUE TITLE
Built-in support for Visual studio project generation for cross platform Android compilation target

### ISSUE THREAD

**Issue by tapika** [premake/premake-core#665]
There already exists some kind of Android support in form of module:

https://groups.google.com/d/topic/premake-development/_Li3KtW6zvA/discussion

but I have tried latest trunk + that module - did not work for me out of box.

I suspect there was some internal API change in premake itself causing backwards compatibility break.

But is it possible to enable built-in support for Android cross compilation ?

I would like to report vlc project set, and that's 35 - 271 projects all together, would really hate to configure each project manually by hand. Also processing their makefile (installing cygwin, etc etc...) on windows also does not sounds a trivial thing to do.

I'm willing to help if will have time for this and you provide sufficient information how integration could happen.

**Comment by samsinsane** [comment]
I'd recommend trying [this module](https://github.com/TurkeyMan/premake-android) instead, I've got a PR open for it to add 2015 support which I recently updated to the latest Premake, you can get it from [here](https://github.com/LORgames/premake-android/tree/ssurtees/vs2015).

I'd be slightly interested in seeing some of the VS2015 cross-compilation projects being supported as they're available from the VS2015 installer. @starkos, @tvandijck, @TurkeyMan thoughts? I'm a bit biased since I've worked on modules to extend the VS exporter for WinRT and Android (specifically the Microsoft implementation) support. I'm happy to defer this decision to you guys, since I will only benefit from these modules being in core.

**Comment by tapika** [comment]
Can you tell me exact integration steps how to enable your project building ?

I have cloned git from https://github.com/premake/premake-core.git
Then cloned https://github.com/TurkeyMan/premake-android.git into modules\premake-android
Listed your module in src\_modules.lua

When building using premake (with --scripts option), following error / warning is displayed:

```
** Warning: module 'premake-android' should return function from _preload.lua
Error: no such action 'android'
```

Also why I did not use your android support originally was link to - https://github.com/gavinpugh/vs-android - I've suspected that I need to install some 3-rd party visual studio extension, and I want to have native / built in android support (from Visual studio). Main reason is not to get only compilation working, but also debugging. And using 3-rd party visual studio extension it's possible that not everything could be supported. But maybe I'm wrong ?

**Comment by tapika** [comment]
Btw - android support from second git ( https://github.com/akaStiX/premake-vsandroid.git ) repository - problem with it is listed here:

https://groups.google.com/forum/#!topic/premake-development/HqIiOO7e0UY/discussion

Also not so usable.

**Comment by samsinsane** [comment]
I guess neither of these modules support being compiled into Premake. I'd recommend just creating a folder beside your `premake5.exe` called `modules` and put your modules there instead. Your folder layout should look this this:

```
premake5.exe
modules/
  android/
    _manifest.lua
    _preload.lua
    ... The rest of the files
```

Once you've done this, you can just add `require "android"` to the top of your Premake5.lua script.

It's up to you which module you'd prefer to use, the one that @TurkeyMan created does support the vs-android extension for VS2010-VS2013, but with my PR it also supports the built-in VS2015 solution.

Again, it's up to you which one you pick, both will achieve the same result more or less.

**Comment by tapika** [comment]
Can you write down all patch sequences - I have tried this and that, none worked out of box.

I assume that you're talking about https://github.com/akaStiX/premake-vsandroid - and it adds support for built-in vs2015 android support ?

So basically my steps so far were following:

1. git clone https://github.com/premake/premake-core.git  - into some premake\ folder.
2. git clone https://github.com/akaStiX/premake-vsandroid. Copy under premake\modules\android
folder, so that folder structure would be:

```
premake\
   modules\
       android\
           _manifest.lua
           _preload.lua
           ... rest of files ...
```

3. After that I have tried to patch src\\_modules.lua, and also tried to use require "android", and after that executed premake with vs2015 or android as a target , but there is either error or does not work as expected.

Please notice that I suspect that newer premake trunk does not work with newest premake-vsandroid -trunk.

**Comment by samsinsane** [comment]
Unfortunately, I'm not really sure what you're trying to achieve here, so it's hard to provide any steps. As I've said before, it doesn't look like it supports being embedded in Premake. "Embedded in Premake" means touching that `_modules.lua` file and then compiling Premake.

If you need the module to be embedded then you'll need to open an issue with that project instead.

If you don't need the module to be embedded and you just want to use it, do the following:
1. Clone Premake
2. Build Premake
3. Beside the Premake binary create a folder called `modules`
4. Inside `modules` create a folder called `vsandroid`
5. Inside `vsandroid` clone the module folder (as described above so that `vsandroid` is the root folder)
6. Add `require "vsandroid"` to the top of your `premake5.lua` file
7. Run `premake5.exe android`

There are links to example configurations in the readme for that module. I recommend you check those out to see what APIs you'll need to call to change different things. As I said above, I haven't used this module so you might have other issues, you'll need to open an issue over there on how to use it.
