### ISSUE TITLE
Can this tool be updated to include and create .swift files?

### ISSUE THREAD

**Issue by mingsai** [premake/premake-core#667]
I quickly scanned some source under the Xcode support and didn't see anything. Just wondering whether it's possible and planned to support Xcode projects using Swift (.swift) files?

**Comment by starkos** [comment]
It is certainly possible; I don't know if it is currently on anyone's radar. If you could identify what needs to change in the files that Premake generates, it might not be a difficult fix.

**Comment by samsinsane** [comment]
I don't know what a `.swift` file is (I'm guessing it's Swift source code?), but I don't see why Premake couldn't support it? As far as I'm aware, we don't have a plan to add support for Swift, but that doesn't mean you can't contribute support for it. I'm sure that @starkos would love some more contributors for Xcode.

@starkos I imagine that this support would have to be done straight into core since the Xcode exporter is a bit tough to override from a module?

**Comment by starkos** [comment]
> I imagine that this support would have to be done straight into core since the Xcode exporter is a bit tough to override from a module?

Yes, it makes sense that support would be added to both Xcode and, ideally, the Makefile exporter as well.
