### ISSUE TITLE
"Unsupported language 'C++11'" on Windows and Linux

### ISSUE THREAD

**Issue by Jusonex** [premake/premake-core#750]
On Windows and Linux, premake complained about the `C++11` flag being deprecated. So I replaced all occurrences of `language "C++"` with `language "C++11"` and removed `flags {"C++11"}`.

Now, it says:
```** Warning: Unsupported language 'C++11' used for project '...'```

Am I doing something wrong or is there a problem in premake?

**Comment by neico** [comment]
I think there's more details needed, can you provide a premake file that is able to reproduce the case?
Because the deprecation is in the same PR as the `language` change and should therefore work.

And which version (build / git sha) are you using to build premake?

**Comment by Jusonex** [comment]
gcc doesn't work for me either. I'm on the current HEAD (74b2f4680e39994c23cf003b8373308ca7480cd6)

I used the following configuration:
```lua
workspace "TestWorkspace"
	configurations { "Debug", "Release" }

	project "TestProject"
		language "C++11"
		kind "ConsoleApp"
```
...and got the error:
```$ premake5 gmake
Building configurations...
** Warning: Unsupported language 'C++11' used for project 'TestProject'
```

I suspect it's this line: https://github.com/premake/premake-core/blob/master/src/actions/make/_make.lua#L25 (which appears identically for all VS build actions)

**Comment by samsinsane** [comment]
@Jusonex that's definitely the issue there. @tvandijck should the actions specify every standard they support? Or should they continue to specify the languages, and a reverse lookup is performed to find the appropriate table in `premake.languages` to perform the check or something similar?

I don't really think there's a clean way to handle `valid_languages` with the standards added in. We either end up having to do something about the .NET languages so that new ones aren't automatically handled by gmake and all versions of VS, or specify the language and standards explicitly for each action. The latter results in some interesting questions about how to handle VS2005-VS2013, which really only support a single standard for C++.

**Comment by tvandijck** [comment]
Good question, and I'm sorry for the unexpected problem.... we should add tests to cover these cases so we never regress again...

that said, the quick fix is to add all the supported languages, but I don't think that that is maintainable long term. The alternative would be to simply remove it for now, and come up with a different way to support thing kind of validation... a callback for example could probably be made to work more easily.

**Comment by Jusonex** [comment]
Great! Thanks for reacting so fast. 👍
