### ISSUE TITLE
Disable precompiled headers on a per-file basis

### ISSUE THREAD

**Issue by cwaldren** [premake/premake-core#762]
Not sure if this has been addressed - have not found any documentation surrounding this.

In Visual Studio, one can enable precompiled headers for the entire project, but then disable them on specific files. This is extremely useful when including external files which don't use PCH or are autogenerated frequently. 

The workaround is to generate the project files and then go in and manually edit the PCH usage within Visual Studio. This means that every time the project files are regenerated, I must remember to redo this step, and tell other developers to do this step.

I may be missing a simple fix. If so I would love to know it!

**Comment by tvandijck** [comment]
This doesn't work??
```
filter { 'files:myfile.cpp' }
   flags { 'NoPCH' }
```

**Comment by cwaldren** [comment]
That absolutely does work. Thanks.

The only other problem is that `stdafx.cpp` is set to`/Yu` instead of `/Yc`, but I can change that manually.

**Comment by Asubayo** [comment]
I would like to succeed to do exactly the same thing as you !
But sadly it seems that the filter on a specific file doesn't work at all for me
I have : 

```
pchheader "project/StdAfx.h"
pchsource "../project/source/project/StdAfx.cpp"
```
And I think it is correct because when I don't try to disable pch on a specific file, the project's precompiled header property is "Use" and on the StdAfx.cpp, the value is "Create"

But as soon as I use : 

```
filter { 'files:myfile.cpp' }
   flags { 'NoPCH' }
```
Everything is set to "Not Using" (on the project settings, on every files, on StdAfx.cpp)
It is like the filter doesn't work and the NoPCH flag is applied to the whole project. I don't get it, any idea ?
