### ISSUE TITLE
The flag NoPCH is not working for the VC2000x versions

### ISSUE THREAD

**Issue by fixItSoon** [premake/premake-core#777]
The flag NoPCH is not working for the VC2000x versions if used in filters, example:

```
filter {"files:**.c"}
    flags { "NoPCH" }
```
To fix the problem, change the code in the vs200x_vcproj.lua to:
```
function m.usePrecompiledHeader(cfg)
	local prj, file = config.normalize(cfg)
	if file then
		if prj.pchsource == file.abspath and
		   not prj.flags.NoPCH and
		   prj.system == p.WINDOWS
		then
		   p.w('UsePrecompiledHeader="1"')
             elseif file.flags.NoPCH then
		   p.w('UsePrecompiledHeader="0"')
	      end
	   else
	      if not prj.flags.NoPCH and prj.pchheader then
		  p.w('UsePrecompiledHeader="%s"', iif(_ACTION < "vs2005", 3, 2))
		  p.x('PrecompiledHeaderThrough="%s"', prj.pchheader)
	      else
		   p.w('UsePrecompiledHeader="%s"', iif(_ACTION > "vs2003" or prj.flags.NoPCH, 0, 2))
	      end
	end
end

**Comment by samsinsane** [comment]
Despite the obvious troll account name, I've submitted a PR for this.

In the future, please feel free to submit a PR with your solution. Due to lack of time and personal incentive, VS200x bugs are unlikely to be as I doubt enough contributors have access to these decade old versions to test with. Additionally, I imagine these actions will eventually be removed from Premake-core due to the products being end of life.
