### ISSUE TITLE
language:D not linking to static libs on vstudio (2017)

### ISSUE THREAD

**Issue by zpgaal** [premake/premake-core#791]
D generates a different vcproj files.
If NoImplicitLink is not provided, it will remove the links. and program linking fails:

project "proj_lib"
	kind "StaticLib"
	language "D"
	files { "**.d" }

project "proj_bin"
	kind "ConsoleApp"
	language "D"
	files { "**.d" }
	links { "proj_lib" }  

 --- removes proj_lib from the link: <libfiles> will be empty as it tries to rely only on dependency and implicit linking, which seems not to work for D

**Comment by tvandijck** [comment]
Unfortunately, we currently have no active D experts or maintainers. So unless @TurkeyMan wants to chime in and look at this, I don't think we have anyone that could fix this.

**Comment by TurkeyMan** [comment]
This is an issue with VisualD. Implicit linking works, just that it doesn't seem to init form the project file, and stores the setting in the user settings file.
Fix: generate the project, right click solution -> project dependencies, make sure the tickboxes are appropriately set for each project in the drop-down box (ie, exe depends on lib project).
Implicit linking should work properly now... at least, it does for me when I encounter this issue.

The latest version of VisualD no longer creates its own project format, and integrates into C/C++ .vcxproj files, I have most-working code to support the new project scheme, I was waiting for a non-beta release of VisualD to deploy it, also it needs a few more tweaks.

I've had almost no time to work on side stuff recently, mostly due to health reasons and trying to keep the ship afloat >_< ... Hoping to get back at it again soon enough.

**Comment by tvandijck** [comment]
@TurkeyMan it's good to hear from you again though ;)

**Comment by samsinsane** [comment]
Closing this as I believe Premake now generates the integrated project format mentioned above. If you're still experiencing issues after changing `language` to `"C++"`, please feel free to reopen this.
