### ISSUE TITLE
os.copyfile() fails on premake-5.0.0-alpha12 on Windows

### ISSUE THREAD

**Issue by pjohalloran** [premake/premake-core#918]
Hi,

I wrote a premake5 script for the OSX platform first which works as expected.

When i run the same script on Windows 10 on premake5 version 5.0.0-alpha12, i get an error when using `os.copyfile()`.

The error is: `unable to copy file to $path`.

I checked and the target directory exists and is a directory. The file I am trying to copy also exists. I checked by manually inspecting my filesystem and also using `os.isdir()` and `os.isfile()` in my build script before i attempt the copy operation.

Any ideas?

**Comment by starkos** [comment]
That error message is written in [os_copyfile.c](https://github.com/premake/premake-core/blob/master/src/host/os_copyfile.c#L41)

```
lua_pushfstring(L, "unable to copy file to '%s'", dst);
```

Based on your error message, it looks like you are passing in the literal string "$path" to the call. Windows isn't going to have any idea what to do with that. If you are trying to expand an environment variable, you will need to use "%path%".

I am going to make this as closed, since that is definitely what is tripping Windows up. But feel free to reopen with more information if you need help getting things working!

**Comment by pjohalloran** [comment]
No, I just put `$path` in as I didnt want to put in a long path clouding up the error :)

Lets say path equals `C:\tmp` then.

**Comment by starkos** [comment]
Reopening…I'm not on a Windows box right now to test. The [code for `copyfile()` is here](https://github.com/premake/premake-core/blob/master/src/host/os_copyfile.c#L41) if you want to try to figure out where it is falling down? Otherwise, we'll try to reproduce the issue. The paths in your previous comment are the ones we should using as a reproduction case?

**Comment by pjohalloran** [comment]
Cool thanks, ill have a look at that this evening. Code certainly looks like it should be ok...  The paths above are not exactly the ones i used but are close.

**Comment by pjohalloran** [comment]
I modifed the premake source to give extra information on why the copy failed on windows. Im getting error code back from CopyFileW (ERROR_ACCESS_DENIED).

This can happen if the file is marked as read only, except in my case, it is not. Not sure what to do to fix the error. 

I can put in a pull request to add extra error information for when things fail for os.copyfile() at least?

**Comment by starkos** [comment]
> I can put in a pull request to add extra error information for when things fail for os.copyfile() at least?

I think that would certainly be worthwhile!

**Comment by pjohalloran** [comment]
How does this look?
https://github.com/premake/premake-core/pull/932

**Comment by pjohalloran** [comment]
By the way, my error message, original problem is this:

```Executing C:/Users/pjoha/work/ember/projects/thirdparty_build_scripts/filesystem.lua for Lib: filesystem
Failed to copy C:/Users/pjoha/work/ember/src/thirdparty/filesystem/filesystem/fwd.h to target "C:/Users/pjoha/work/ember/include/filesystem"
Reason: unable to copy file to 'C:/Users/pjoha/work/ember/include/filesystem', reason: 'Access is denied.
'```

**Comment by samsinsane** [comment]
According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363851(v=vs.85).aspx) the second parameter to `CopyFileW` should be a file name. [This stackoverflow post](https://stackoverflow.com/questions/45105179/how-to-fix-copyfile-error-5-access-denied-error) covers the issue, it's a bit annoying that it uses "access denied" instead of something sane like "destination is a folder".

**Comment by starkos** [comment]
This does look like the likely culprit. Regardless, I think we've identified that the issue is not with Premake per se so I am going to go ahead and mark this issue as closed for now. Feel free to reopen it if you have more questions though!

**Comment by pjohalloran** [comment]
Cool thanks.
